#!/bin/sh
# Verify that every proved theorem uses only Palomar's permitted axioms.
set -eu
cd "$(dirname "$0")/.."

BASE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/\1/p' Max11Core.lean)"
ROUTE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11ClassicalRoutes.\1/p' ClassicalRoutes.lean)"
DEGREE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' DegreeRoutes.lean)"
HISTORY_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' HistoryRoute.lean)"
HISTORY_DEGREE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' HistoryDegree.lean)"
TOTAL_DEGREE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' TotalDegreeRoutes.lean)"
COPRIME_DEGREE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' CoprimeDegreeRoute.lean)"
ENDPOINT_GCD_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' EndpointGCDRoute.lean)"
LOW_SCALE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScaleCore.lean)"
LOW_SCALE_46_ROW_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46Rows.lean)"
LOW_SCALE_46_NORMAL_FORM_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46NormalForm.lean)"
LOW_SCALE_46_CURVE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46Curve.lean)"
LOW_SCALE_46_LOCAL_CHART_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46LocalChart.lean)"
LOW_SCALE_46_ALIGNED_CHART_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46AlignedChart.lean)"
LOW_SCALE_46_DEGREE_CONE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46DegreeCones.lean)"
LOW_SCALE_46_DEPRESSION_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46Depression.lean)"
LOW_SCALE_46_INTEGRALITY_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46Integrality.lean)"
LOW_SCALE_46_QUADRATIC_FIELD_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46QuadraticField.lean)"
LOW_SCALE_46_QUADRATIC_SOURCE_BRIDGE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46QuadraticSourceBridge.lean)"
LOW_SCALE_46_QUADRATIC_ENDGAME_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46QuadraticEndgame.lean)"
LOW_SCALE_46_NEWTON_FACE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46NewtonFaces.lean)"
LOW_SCALE_46_POLYNOMIAL_ENDGAME_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46PolynomialEndgame.lean)"
LOW_SCALE_46_FINITE_POLE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46FinitePoles.lean)"
LOW_SCALE_46_ALIGNED_FINITE_POLE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46AlignedFinitePoles.lean)"
LOW_SCALE_46_ALIGNED_POLYNOMIAL_ENDGAME_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46AlignedPolynomialEndgame.lean)"
LOW_SCALE_46_ALIGNED_ZERO_FINITE_POLE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46AlignedZeroFinitePoles.lean)"
LOW_SCALE_46_ALIGNED_COMPONENT_ENDGAME_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46AlignedComponentEndgame.lean)"
LOW_SCALE_46_SOURCE_BRIDGE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46SourceBridge.lean)"
LOW_SCALE_46_GENERAL_SOURCE_BRIDGE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46GeneralSourceBridge.lean)"
LOW_SCALE_46_SCALE_ZERO_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46ScaleZero.lean)"
LOW_SCALE_46_POLE_BRIDGE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46PoleBridge.lean)"
LOW_SCALE_46_REGULAR_LOAD_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46RegularLoads.lean)"
LOW_SCALE_46_ALIGNED_REGULAR_LOAD_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46AlignedRegularLoads.lean)"
LOW_SCALE_46_WEIGHTED_INFINITY_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46WeightedInfinity.lean)"
LOW_SCALE_46_SCALE_TWO_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale46ScaleTwo.lean)"
LOW_SCALE_68_NORMAL_FORM_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68NormalForm.lean)"
LOW_SCALE_68_INTEGRATED_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68Integrated.lean)"
LOW_SCALE_68_DEPRESSION_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68Depression.lean)"
LOW_SCALE_68_SOURCE_BRIDGE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SourceBridge.lean)"
LOW_SCALE_68_SCALE_ZERO_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68ScaleZero.lean)"
LOW_SCALE_68_INFINITY_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68Infinity.lean)"
LOW_SCALE_68_POLYNOMIAL_BOUNDARY_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68PolynomialBoundary.lean)"
LOW_SCALE_68_WEIGHTED_RADIUS_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68WeightedRadius.lean)"
LOW_SCALE_68_EXPANSION_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68Expansion.lean)"
LOW_SCALE_68_CUBIC_DESCENT_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68CubicDescent.lean)"
LOW_SCALE_68_SECONDARY_RADIUS_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryRadius.lean)"
LOW_SCALE_68_SECONDARY_FACE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryFace.lean)"
LOW_SCALE_68_SECONDARY_EXTRACTION_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryExtraction.lean)"
LOW_SCALE_68_SECONDARY_ONE_FORM_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryOneForms.lean)"
LOW_SCALE_68_SECONDARY_SMALL_GAP_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondarySmallGap.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_FACE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualFace.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_EXTRACTION_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualExtraction.lean)"
LOW_SCALE_68_SECONDARY_LARGE_GAP_LOAD_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryLargeGapLoads.lean)"
LOW_SCALE_68_SECONDARY_RELAXED_FIRST_FACE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryRelaxedFirstFace.lean)"
LOW_SCALE_68_SECONDARY_RELAXED_CANONICAL_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryRelaxedCanonical.lean)"
LOW_SCALE_68_SECONDARY_ALPHA_WALL_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryAlphaWall.lean)"
LOW_SCALE_68_SECONDARY_ALPHA_WALL_CANONICAL_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryAlphaWallCanonical.lean)"
LOW_SCALE_68_SECONDARY_FIRST_LOAD_WALL_FACE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryFirstLoadWallFace.lean)"
LOW_SCALE_68_SECONDARY_FIRST_LOAD_WALL_CORE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryFirstLoadWallCore.lean)"
LOW_SCALE_68_SECONDARY_FIRST_LOAD_WALL_REMAINDER_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryFirstLoadWallRemainder.lean)"
LOW_SCALE_68_SECONDARY_FIRST_LOAD_WALL_CANONICAL_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryFirstLoadWallCanonical.lean)"
LOW_SCALE_68_SECONDARY_FIRST_GAP_BOUNDARY_FACE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryFirstGapBoundaryFace.lean)"
LOW_SCALE_68_SECONDARY_FIRST_GAP_BOUNDARY_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryFirstGapBoundary.lean)"
LOW_SCALE_68_SECONDARY_LARGE_GAP_RESIDUAL_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryLargeGapResidual.lean)"
LOW_SCALE_68_SECONDARY_LARGE_GAP_LOAD_ZERO_FACE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryLargeGapLoadZeroFace.lean)"
LOW_SCALE_68_SECONDARY_LARGE_GAP_SUBCRITICAL_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryLargeGapSubcritical.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_MIDDLE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualMiddle.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_DOUBLE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualDouble.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_DOUBLE_LOAD_WALL_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualDoubleLoadWall.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_DOUBLE_LOAD_WALL_CANONICAL_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualDoubleLoadWallCanonical.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_SUM_LOAD_WALL_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualSumLoadWall.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_HALF_RADIUS_LOAD_WALL_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualHalfRadiusLoadWall.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_HALF_RADIUS_I4_WALL_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualHalfRadiusI4Wall.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_HALF_RADIUS_BOUNDARY_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualHalfRadiusBoundary.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_LEFT_LOAD_WINDOW_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualLeftLoadWindow.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_LEFT_BOUNDARY_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualLeftBoundary.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_ROW_TWO_LOAD_DOMINANCE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualRowTwoLoadDominance.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_OVERSHOOT_CANONICAL_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualOvershootCanonical.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_OVERSHOOT_BOUNDARY_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualOvershootBoundary.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_THREE_GAP_BOUNDARY_MIDDLE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualThreeGapBoundaryMiddle.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_THREE_GAP_BOUNDARY_SELECTOR_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualThreeGapBoundarySelector.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_STRIP_SELECTOR_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualStripSelector.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_SELECTOR_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualSelector.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_DESCENT_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualDescent.lean)"
ASSEMBLY_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' Max11Assembly.lean)"
THEOREMS="$BASE_THEOREMS $ROUTE_THEOREMS $DEGREE_THEOREMS $HISTORY_THEOREMS $HISTORY_DEGREE_THEOREMS $TOTAL_DEGREE_THEOREMS $COPRIME_DEGREE_THEOREMS $ENDPOINT_GCD_THEOREMS $LOW_SCALE_THEOREMS $LOW_SCALE_46_ROW_THEOREMS $LOW_SCALE_46_NORMAL_FORM_THEOREMS $LOW_SCALE_46_CURVE_THEOREMS $LOW_SCALE_46_LOCAL_CHART_THEOREMS $LOW_SCALE_46_ALIGNED_CHART_THEOREMS $LOW_SCALE_46_DEGREE_CONE_THEOREMS $LOW_SCALE_46_DEPRESSION_THEOREMS $LOW_SCALE_46_INTEGRALITY_THEOREMS $LOW_SCALE_46_QUADRATIC_FIELD_THEOREMS $LOW_SCALE_46_QUADRATIC_SOURCE_BRIDGE_THEOREMS $LOW_SCALE_46_QUADRATIC_ENDGAME_THEOREMS $LOW_SCALE_46_NEWTON_FACE_THEOREMS $LOW_SCALE_46_POLYNOMIAL_ENDGAME_THEOREMS $LOW_SCALE_46_FINITE_POLE_THEOREMS $LOW_SCALE_46_ALIGNED_FINITE_POLE_THEOREMS $LOW_SCALE_46_ALIGNED_POLYNOMIAL_ENDGAME_THEOREMS $LOW_SCALE_46_ALIGNED_ZERO_FINITE_POLE_THEOREMS $LOW_SCALE_46_ALIGNED_COMPONENT_ENDGAME_THEOREMS $LOW_SCALE_46_SOURCE_BRIDGE_THEOREMS $LOW_SCALE_46_GENERAL_SOURCE_BRIDGE_THEOREMS $LOW_SCALE_46_SCALE_ZERO_THEOREMS $LOW_SCALE_46_POLE_BRIDGE_THEOREMS $LOW_SCALE_46_REGULAR_LOAD_THEOREMS $LOW_SCALE_46_ALIGNED_REGULAR_LOAD_THEOREMS $LOW_SCALE_46_WEIGHTED_INFINITY_THEOREMS $LOW_SCALE_46_SCALE_TWO_THEOREMS $LOW_SCALE_68_NORMAL_FORM_THEOREMS $LOW_SCALE_68_INTEGRATED_THEOREMS $LOW_SCALE_68_DEPRESSION_THEOREMS $LOW_SCALE_68_SOURCE_BRIDGE_THEOREMS $LOW_SCALE_68_SCALE_ZERO_THEOREMS $LOW_SCALE_68_INFINITY_THEOREMS $LOW_SCALE_68_POLYNOMIAL_BOUNDARY_THEOREMS $LOW_SCALE_68_WEIGHTED_RADIUS_THEOREMS $LOW_SCALE_68_EXPANSION_THEOREMS $LOW_SCALE_68_CUBIC_DESCENT_THEOREMS $LOW_SCALE_68_SECONDARY_RADIUS_THEOREMS $LOW_SCALE_68_SECONDARY_FACE_THEOREMS $LOW_SCALE_68_SECONDARY_EXTRACTION_THEOREMS $LOW_SCALE_68_SECONDARY_ONE_FORM_THEOREMS $LOW_SCALE_68_SECONDARY_SMALL_GAP_THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_FACE_THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_EXTRACTION_THEOREMS $LOW_SCALE_68_SECONDARY_LARGE_GAP_LOAD_THEOREMS $LOW_SCALE_68_SECONDARY_RELAXED_FIRST_FACE_THEOREMS $LOW_SCALE_68_SECONDARY_RELAXED_CANONICAL_THEOREMS $LOW_SCALE_68_SECONDARY_FIRST_LOAD_WALL_FACE_THEOREMS $LOW_SCALE_68_SECONDARY_FIRST_LOAD_WALL_CORE_THEOREMS $LOW_SCALE_68_SECONDARY_LARGE_GAP_RESIDUAL_THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_MIDDLE_THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_DOUBLE_THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_SELECTOR_THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_DESCENT_THEOREMS $ASSEMBLY_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_ALPHA_WALL_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_ALPHA_WALL_CANONICAL_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_FIRST_LOAD_WALL_REMAINDER_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_HALF_RADIUS_LOAD_WALL_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_HALF_RADIUS_I4_WALL_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_HALF_RADIUS_BOUNDARY_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_LEFT_BOUNDARY_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_FIRST_LOAD_WALL_CANONICAL_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_FIRST_GAP_BOUNDARY_FACE_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_FIRST_GAP_BOUNDARY_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_LARGE_GAP_LOAD_ZERO_FACE_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_LARGE_GAP_SUBCRITICAL_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_DOUBLE_LOAD_WALL_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_DOUBLE_LOAD_WALL_CANONICAL_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_SUM_LOAD_WALL_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_LEFT_LOAD_WINDOW_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_ROW_TWO_LOAD_DOMINANCE_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_OVERSHOOT_CANONICAL_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_OVERSHOOT_BOUNDARY_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_THREE_GAP_BOUNDARY_MIDDLE_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_THREE_GAP_BOUNDARY_SELECTOR_THEOREMS"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_STRIP_SELECTOR_THEOREMS"
PROBE="import Max11Assembly\nimport LowScale46ScaleTwo\nimport LowScale68NormalForm\nimport LowScale68Integrated\nimport LowScale68Depression\nimport LowScale68SourceBridge\nimport LowScale68ScaleZero\nimport LowScale68Infinity\nimport LowScale68PolynomialBoundary\nimport LowScale68WeightedRadius\nimport LowScale68Expansion\nimport LowScale68CubicDescent\nimport LowScale68SecondaryRadius\nimport LowScale68SecondaryFace\nimport LowScale68SecondaryExtraction\nimport LowScale68SecondaryOneForms\nimport LowScale68SecondarySmallGap\n"
PROBE="${PROBE}import LowScale68SecondaryResidualFace\n"
PROBE="${PROBE}import LowScale68SecondaryResidualExtraction\n"
PROBE="${PROBE}import LowScale68SecondaryLargeGapLoads\n"
PROBE="${PROBE}import LowScale68SecondaryRelaxedFirstFace\n"
PROBE="${PROBE}import LowScale68SecondaryRelaxedCanonical\n"
PROBE="${PROBE}import LowScale68SecondaryAlphaWall\n"
PROBE="${PROBE}import LowScale68SecondaryAlphaWallCanonical\n"
PROBE="${PROBE}import LowScale68SecondaryFirstLoadWallFace\n"
PROBE="${PROBE}import LowScale68SecondaryFirstLoadWallCore\n"
PROBE="${PROBE}import LowScale68SecondaryFirstLoadWallRemainder\n"
PROBE="${PROBE}import LowScale68SecondaryFirstLoadWallCanonical\n"
PROBE="${PROBE}import LowScale68SecondaryFirstGapBoundaryFace\n"
PROBE="${PROBE}import LowScale68SecondaryFirstGapBoundary\n"
PROBE="${PROBE}import LowScale68SecondaryLargeGapResidual\n"
PROBE="${PROBE}import LowScale68SecondaryLargeGapLoadZeroFace\n"
PROBE="${PROBE}import LowScale68SecondaryLargeGapSubcritical\n"
PROBE="${PROBE}import LowScale68SecondaryResidualMiddle\n"
PROBE="${PROBE}import LowScale68SecondaryResidualDouble\n"
PROBE="${PROBE}import LowScale68SecondaryResidualDoubleLoadWall\n"
PROBE="${PROBE}import LowScale68SecondaryResidualDoubleLoadWallCanonical\n"
PROBE="${PROBE}import LowScale68SecondaryResidualSumLoadWall\n"
PROBE="${PROBE}import LowScale68SecondaryResidualHalfRadiusLoadWall\n"
PROBE="${PROBE}import LowScale68SecondaryResidualHalfRadiusI4Wall\n"
PROBE="${PROBE}import LowScale68SecondaryResidualHalfRadiusBoundary\n"
PROBE="${PROBE}import LowScale68SecondaryResidualLeftLoadWindow\n"
PROBE="${PROBE}import LowScale68SecondaryResidualLeftBoundary\n"
PROBE="${PROBE}import LowScale68SecondaryResidualRowTwoLoadDominance\n"
PROBE="${PROBE}import LowScale68SecondaryResidualOvershootCanonical\n"
PROBE="${PROBE}import LowScale68SecondaryResidualOvershootBoundary\n"
PROBE="${PROBE}import LowScale68SecondaryResidualThreeGapBoundaryMiddle\n"
PROBE="${PROBE}import LowScale68SecondaryResidualThreeGapBoundarySelector\n"
PROBE="${PROBE}import LowScale68SecondaryResidualStripSelector\n"
PROBE="${PROBE}import LowScale68SecondaryResidualSelector\n"
PROBE="${PROBE}import LowScale68SecondaryResidualDescent\n"
LOW_SCALE_68_SECONDARY_RESIDUAL_ROW_TWO_SYSTEM_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualRowTwoSystem.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_ROW_TWO_FACES_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualRowTwoFaces.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_ROW_TWO_BALANCED_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualRowTwoBalanced.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_BALANCED_SELECTOR_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualBalancedSelector.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_CANONICAL_BALANCED_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualCanonicalBalanced.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_CANONICAL_BALANCED_DATA_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualCanonicalBalancedData.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_ROW_ONE_FACES_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualRowOneFaces.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_ROW_ONE_SYSTEM_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualRowOneSystem.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_BALANCED_ENDGAME_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualBalancedEndgame.lean)"
LOW_SCALE_68_SECONDARY_RESIDUAL_LOAD_ZERO_ENDGAME_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' LowScale68SecondaryResidualLoadZeroEndgame.lean)"
THEOREMS="$THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_ROW_TWO_SYSTEM_THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_ROW_TWO_FACES_THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_ROW_TWO_BALANCED_THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_BALANCED_SELECTOR_THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_CANONICAL_BALANCED_THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_CANONICAL_BALANCED_DATA_THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_ROW_ONE_FACES_THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_ROW_ONE_SYSTEM_THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_BALANCED_ENDGAME_THEOREMS $LOW_SCALE_68_SECONDARY_RESIDUAL_LOAD_ZERO_ENDGAME_THEOREMS"
PROBE="${PROBE}import LowScale68SecondaryResidualRowTwoSystem\n"
PROBE="${PROBE}import LowScale68SecondaryResidualRowTwoFaces\n"
PROBE="${PROBE}import LowScale68SecondaryResidualRowTwoBalanced\n"
PROBE="${PROBE}import LowScale68SecondaryResidualBalancedSelector\n"
PROBE="${PROBE}import LowScale68SecondaryResidualCanonicalBalanced\n"
PROBE="${PROBE}import LowScale68SecondaryResidualCanonicalBalancedData\n"
PROBE="${PROBE}import LowScale68SecondaryResidualRowOneFaces\n"
PROBE="${PROBE}import LowScale68SecondaryResidualRowOneSystem\n"
PROBE="${PROBE}import LowScale68SecondaryResidualBalancedEndgame\n"
PROBE="${PROBE}import LowScale68SecondaryResidualLoadZeroEndgame\n"
RECENT_MODULES="LowScale410NormalForm LowScale410FirstIntegrals LowScale410ZeroLoadTrajectory LowScale410ZeroLoadShiftedFiber LowScale410LoadCascade LowScale410LWall LowScale410LWallBoundary LowScale410LWallResidual LowScale410LWallOtherCones LowScale410LWallFanConnector LowScale410LWallUnconditional LowScale410ScaleTwoSourceFace LowScale610ScaleTwoSourceFace LowScale810ScaleTwoSourceFace LowScale68ScaleZeroAssembly LowScale68ScaleTwoSourceFace LowScale68ScaleTwoNonalignedInfinity LowScale68ScaleTwoLocalInitialForms LowScale68ScaleTwoLocalRowThree LowScale68ScaleTwoLocalDerivativeRowTwo LowScale68ScaleTwoIntegratedBoundary LowScale68ScaleTwoLocalRowOneZero LowScale68ScaleTwoLocalRhoFour LowScale68ScaleTwoLocalRhoThree LowScale68ScaleTwoLocalRhoTwo LowScale68ScaleTwoAfterRhoTwo LowScale68ScaleTwoLocalRhoOne LowScale68ScaleTwoRhoOneTransverse LowScale68ScaleTwoRhoOneComponentSplit LowScale68ScaleTwoRhoOneNoncubicNext LowScale68ScaleTwoRhoOneNoncubicElimination LowScale68ScaleTwoAfterRhoOne LowScale68ScaleTwoAfterRhoOneNextBox LowScale68ScaleTwoAfterRhoOneBranchRows LowScaleRemainingShear LowScale68SecondaryLargeGapAlphaCancellation LowScale68SecondaryAlphaWallEndgame LowScale68SecondaryAlphaWallRowOneLoad LowScale68SecondaryAlphaWallRowTwoLoad LowScale68SecondaryAlphaWallMixedEndgame LowScale68SecondaryAlphaWallBalancedRowZero LowScale68SecondaryDeepGapCascade LowScale68SecondaryDeepGapResidualOneForms LowScale68SecondaryDeepGapResidualEndgame LowScale68SecondaryDeepGapMiddleBetaEndgame LowScale68SecondaryDeepGapMiddleBetaNextOrder LowScale68SecondaryDeepGapMiddleRightEndgame LowScale68SecondaryLaterDeepLoadCascade LowScale68SecondaryLaterDeepLowerEndgame LowScale68SecondaryLaterDeepLowerResidual LowScale68SecondaryLaterDeepThreeRadiusWallNext LowScale68SecondaryLaterDeepThreeRadiusWallElimination LowScale68SecondaryLaterDeepThreeRadiusResidualEntry LowScale68SecondaryLaterDeepMixedTwoNFace LowScale68SecondaryLaterDeepClampedEndgame LowScale68SecondaryLaterDeepPreclampedEndgame LowScale68SecondaryLaterDeepPreclampedLowerEndgame LowScale68SecondaryLaterDeepSixToSevenLowerCoefficient LowScale68SecondaryLaterDeepSevenBoundaryEndgame LowScale68SecondaryLaterDeepFiveToSixEndgame LowScale68SecondaryLaterDeepFiveToSixRowOne LowScale68SecondaryLaterDeepFiveToSixLowerCoefficient LowScale68SecondaryLaterDeepFiveToSixResidualNext LowScale68SecondaryLaterDeepFiveToSixNonzeroEdge LowScale68SecondaryLaterDeepFiveToSixStrideDescent"
for module in $RECENT_MODULES; do
  MODULE_THEOREMS="$(sed -n 's/^theorem \([^ ]*\).*/Max11DegreeRoutes.\1/p' "${module}.lean")"
  THEOREMS="$THEOREMS $MODULE_THEOREMS"
  PROBE="${PROBE}import ${module}\n"
done
for thm in $THEOREMS; do
  PROBE="${PROBE}#print axioms ${thm}\n"
done

OUT="$(printf '%b' "$PROBE" | lake env lean --stdin 2>&1)" || {
  echo "$OUT"
  echo "FAIL: could not elaborate the axiom probe (build first: lake build)"
  exit 1
}
echo "$OUT"

for thm in $THEOREMS; do
  if echo "$OUT" | grep -Fq "'$thm' does not depend on any axioms"; then
    continue
  fi
  BLOCK="$(echo "$OUT" | sed -n "/'$thm' depends on axioms/,/]/p" | head -20)"
  if [ -z "$BLOCK" ]; then
    echo "FAIL: no axiom report for $thm"
    exit 1
  fi
  BAD="$(echo "$BLOCK" | tr '\n' ' ' | sed -e 's/.*axioms: \[//' -e 's/\].*//' -e 's/,/\n/g' \
    | tr -d ' ' | grep -v -E '^(propext|Classical\.choice|Quot\.sound)$' || true)"
  if [ -n "$BAD" ]; then
    echo "FAIL: $thm depends on non-permitted axioms: $BAD"
    exit 1
  fi
done
COUNT="$(printf '%s\n' $THEOREMS | wc -l | tr -d ' ')"
echo "OK: all $COUNT max11-partial-y theorems use only permitted axioms."
