import Fable610ScaleZeroEleventhDefectSpeedTPart01Scratch
import Fable610ScaleZeroEleventhDefectSpeedTPart02Scratch
import Fable610ScaleZeroEleventhDefectSpeedTPart03Scratch
import Fable610ScaleZeroEleventhDefectSpeedTPart101Scratch

/-! Scale-zero eleventh-defect packet, split into six bounded modules.
Public declarations and their section contexts are preserved. -/
