import Grok810ScaleZeroQuarticChamberInnerScratch
import Grok810ScaleZeroQuarticChamberKills4Part0Scratch
import Grok810ScaleZeroQuarticChamberKills4Part1Scratch
import Grok810ScaleZeroQuarticChamberKills4Part2Scratch
import Grok810ScaleZeroQuarticChamberKills4Part3Scratch
import Grok810ScaleZeroQuarticChamberKills4Part4Scratch
import Grok810ScaleZeroQuarticChamberKills4Part5Scratch
import Grok810ScaleZeroQuarticChamberKills4Part6Scratch
import Grok810ScaleZeroQuarticChamberKills4Part7Scratch
import Grok810ScaleZeroQuarticChamberKills4Part8Scratch
import Grok810ScaleZeroQuarticChamberKills4Part9Scratch
import Grok810ScaleZeroQuarticChamberKills4Part10Scratch
import Grok810ScaleZeroQuarticChamberKills4Part11Scratch
import Grok810ScaleZeroQuarticChamberKills4Part12Scratch
import Grok810ScaleZeroQuarticChamberKills4Part13Scratch
import Grok810ScaleZeroQuarticChamberKills4Part14Scratch
import Grok810ScaleZeroQuarticChamberKills4Part15Scratch
import Grok810ScaleZeroQuarticChamberKills4Part16Scratch
import Grok810ScaleZeroQuarticChamberKills4Part17Scratch
import Grok810ScaleZeroQuarticChamberKills4Part18Scratch
import Grok810ScaleZeroQuarticChamberKills4Part19Scratch
import Grok810ScaleZeroQuarticChamberKills4Part20Scratch
import Grok810ScaleZeroQuarticChamberKills4Part21Scratch
import Grok810ScaleZeroQuarticChamberKills4Part22Scratch
import Grok810ScaleZeroQuarticChamberKills4Part23Scratch
import Grok810ScaleZeroQuarticChamberKills4Part24Scratch
import Grok810ScaleZeroQuarticChamberKills4Part25Scratch
import Grok810ScaleZeroQuarticChamberKills4Part26Scratch
import Grok810ScaleZeroQuarticChamberKills4Part27Scratch
import Grok810ScaleZeroQuarticChamberKills4Part28Scratch
import Grok810ScaleZeroQuarticChamberKills4Part29Scratch
import Grok810ScaleZeroQuarticChamberKills4Part30Scratch
import Grok810ScaleZeroQuarticChamberKills4Part31Scratch
import Grok810ScaleZeroQuarticChamberKills4Part32Scratch
import Grok810ScaleZeroQuarticChamberKills4Part33Scratch
import Grok810ScaleZeroQuarticChamberKills4Part34Scratch
import Grok810ScaleZeroQuarticChamberKills4Part35Scratch
import Grok810ScaleZeroQuarticChamberKills4Part36Scratch
import Grok810ScaleZeroQuarticChamberKills4Part37Scratch
import Grok810ScaleZeroQuarticChamberKills4Part38Scratch
import Grok810ScaleZeroQuarticChamberKills4Part39Scratch
import Grok810ScaleZeroQuarticChamberKills4Part40Scratch
import Grok810ScaleZeroQuarticChamberKills4Part41Scratch
import Grok810ScaleZeroQuarticChamberKills4Part42Scratch
import Grok810ScaleZeroQuarticChamberKills4Part43Scratch

/-! # Multi-carrier chamber kills, `(8,10)` scale zero

44 chambers whose certificate needs several faces: each face's top
coefficient is extracted with `…ChamberInnerScratch`'s `_coeff_top`
bridge, and the isobaric identity then contradicts a product of
non-zero leading coefficients.  Untracked working note.
-/

open scoped Polynomial.Bivariate

noncomputable section

open Polynomial

namespace Max11DegreeRoutes

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.unnecessarySeqFocus false
set_option linter.flexible false
set_option linter.style.haveILetI false
set_option linter.unnecessarySimpa false

set_option maxRecDepth 1000000

variable {k : Type*} [Field k] [CharZero k]

section QuarticChamberKills4810

/-! ## Multi-carrier chamber kills -/

end QuarticChamberKills4810

end Max11DegreeRoutes
