import Grok810ScaleZeroQuarticChamberRestsScratch
import Grok810ScaleZeroQuarticChamberKillsPart101Scratch
import Grok810ScaleZeroQuarticChamberKillsPart102Scratch
import Grok810ScaleZeroQuarticChamberKillsPart103Scratch
import Grok810ScaleZeroQuarticChamberKillsPart104Scratch
import Grok810ScaleZeroQuarticChamberKillsPart105Scratch
import Grok810ScaleZeroQuarticChamberKillsPart106Scratch
import Grok810ScaleZeroQuarticChamberKillsPart107Scratch
import Grok810ScaleZeroQuarticChamberKillsPart28Scratch
import Grok810ScaleZeroQuarticChamberKillsPart29Scratch
import Grok810ScaleZeroQuarticChamberKillsPart30Scratch
import Grok810ScaleZeroQuarticChamberKillsPart108Scratch
import Grok810ScaleZeroQuarticChamberKillsPart109Scratch
import Grok810ScaleZeroQuarticChamberKillsPart110Scratch
import Grok810ScaleZeroQuarticChamberKillsPart111Scratch
import Grok810ScaleZeroQuarticChamberKillsPart112Scratch
import Grok810ScaleZeroQuarticChamberKillsPart113Scratch
import Grok810ScaleZeroQuarticChamberKillsPart43Scratch
import Grok810ScaleZeroQuarticChamberKillsPart44Scratch
import Grok810ScaleZeroQuarticChamberKillsPart45Scratch
import Grok810ScaleZeroQuarticChamberKillsPart46Scratch
import Grok810ScaleZeroQuarticChamberKillsPart47Scratch

/-! # Single-monomial chamber kills, `(8,10)` scale zero

11 face-degree lemmas and 550 chamber kills: every leaf whose
level-0 certificate is a single monomial *and* whose eight load columns
are either empty, dominated by the chamber's own ℕ conjuncts, or covered
by the κ band of `…ChamberBandsScratch`.  Which leaves those are is
decided, with exact rational Farkas certificates, by
`scripts/derive_810_quartic_chamber_killplan.py`; the rest are named in
the residual.  Untracked working note.
-/

open scoped Polynomial.Bivariate

noncomputable section

open Polynomial

namespace Max11DegreeRoutes

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.unnecessarySeqFocus false
set_option linter.flexible false
set_option linter.style.haveILetI false
set_option linter.unnecessarySimpa false

set_option maxRecDepth 1000000

variable {k : Type*} [Field k] [CharZero k]

section QuarticChamberKills810

end QuarticChamberKills810

end Max11DegreeRoutes
