import Grok610AlignedSquareSourceWrapperPart03Scratch
import Grok610AlignedSquareSourceWrapperPart07Scratch

noncomputable section
open Polynomial
namespace Max11DegreeRoutes
set_option maxRecDepth 100000000
set_option linter.unusedSectionVars false
set_option linter.unusedVariables false

theorem alignedSquareTowerCeiling610_eq_clearing :
    alignedSquareTowerCeiling610 = alignedSquareSourceClearingPower610 :=
  rfl

end Max11DegreeRoutes
