import Grok810ScaleZeroQuarticChamberRestsScratch
import Grok810ScaleZeroQuarticChamberKillsPart1Scratch
import Grok810ScaleZeroQuarticChamberKillsPart2Scratch
import Grok810ScaleZeroQuarticChamberKillsPart3Scratch
import Grok810ScaleZeroQuarticChamberKillsPart4Scratch
import Grok810ScaleZeroQuarticChamberKillsPart5Scratch
import Grok810ScaleZeroQuarticChamberKillsPart6Scratch
import Grok810ScaleZeroQuarticChamberKillsPart7Scratch
import Grok810ScaleZeroQuarticChamberKillsPart8Scratch
import Grok810ScaleZeroQuarticChamberKillsPart9Scratch
import Grok810ScaleZeroQuarticChamberKillsPart10Scratch
import Grok810ScaleZeroQuarticChamberKillsPart11Scratch
import Grok810ScaleZeroQuarticChamberKillsPart12Scratch
import Grok810ScaleZeroQuarticChamberKillsPart13Scratch
import Grok810ScaleZeroQuarticChamberKillsPart14Scratch
import Grok810ScaleZeroQuarticChamberKillsPart15Scratch
import Grok810ScaleZeroQuarticChamberKillsPart16Scratch
import Grok810ScaleZeroQuarticChamberKillsPart17Scratch
import Grok810ScaleZeroQuarticChamberKillsPart18Scratch
import Grok810ScaleZeroQuarticChamberKillsPart19Scratch
import Grok810ScaleZeroQuarticChamberKillsPart20Scratch
import Grok810ScaleZeroQuarticChamberKillsPart21Scratch
import Grok810ScaleZeroQuarticChamberKillsPart22Scratch
import Grok810ScaleZeroQuarticChamberKillsPart23Scratch
import Grok810ScaleZeroQuarticChamberKillsPart24Scratch
import Grok810ScaleZeroQuarticChamberKillsPart25Scratch
import Grok810ScaleZeroQuarticChamberKillsPart26Scratch
import Grok810ScaleZeroQuarticChamberKillsPart27Scratch
import Grok810ScaleZeroQuarticChamberKillsPart28Scratch
import Grok810ScaleZeroQuarticChamberKillsPart29Scratch
import Grok810ScaleZeroQuarticChamberKillsPart30Scratch
import Grok810ScaleZeroQuarticChamberKillsPart31Scratch
import Grok810ScaleZeroQuarticChamberKillsPart32Scratch
import Grok810ScaleZeroQuarticChamberKillsPart33Scratch
import Grok810ScaleZeroQuarticChamberKillsPart34Scratch
import Grok810ScaleZeroQuarticChamberKillsPart35Scratch
import Grok810ScaleZeroQuarticChamberKillsPart36Scratch
import Grok810ScaleZeroQuarticChamberKillsPart37Scratch
import Grok810ScaleZeroQuarticChamberKillsPart38Scratch
import Grok810ScaleZeroQuarticChamberKillsPart39Scratch
import Grok810ScaleZeroQuarticChamberKillsPart40Scratch
import Grok810ScaleZeroQuarticChamberKillsPart41Scratch
import Grok810ScaleZeroQuarticChamberKillsPart42Scratch
import Grok810ScaleZeroQuarticChamberKillsPart43Scratch
import Grok810ScaleZeroQuarticChamberKillsPart44Scratch
import Grok810ScaleZeroQuarticChamberKillsPart45Scratch
import Grok810ScaleZeroQuarticChamberKillsPart46Scratch
import Grok810ScaleZeroQuarticChamberKillsPart47Scratch

/-! # Single-monomial chamber kills, `(8,10)` scale zero

11 face-degree lemmas and 550 chamber kills: every leaf whose
level-0 certificate is a single monomial *and* whose eight load columns
are either empty, dominated by the chamber's own ℕ conjuncts, or covered
by the κ band of `…ChamberBandsScratch`.  Which leaves those are is
decided, with exact rational Farkas certificates, by
`scripts/derive_810_quartic_chamber_killplan.py`; the rest are named in
the residual.  Untracked working note.
-/

open scoped Polynomial.Bivariate

noncomputable section

open Polynomial

namespace Max11DegreeRoutes

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.unnecessarySeqFocus false
set_option linter.flexible false
set_option linter.style.haveILetI false
set_option linter.unnecessarySimpa false

set_option maxRecDepth 1000000

variable {k : Type*} [Field k] [CharZero k]

section QuarticChamberKills810

end QuarticChamberKills810

end Max11DegreeRoutes
