import Grok810ScaleZeroQuarticChamberFacesScratch
import Grok810ScaleZeroQuarticChamberColumnsScratch
import Grok810ScaleZeroQuarticChamberRestsScratch
import Grok810ScaleZeroQuarticChamberKillsScratch
import Grok810ScaleZeroQuarticChamberColumns2Scratch
import Grok810ScaleZeroQuarticChamberRests2Scratch
import Grok810ScaleZeroQuarticChamberKills2Scratch
import Grok810ScaleZeroQuarticChamberNuFacesScratch
import Grok810ScaleZeroQuarticChamberColumns3Scratch
import Grok810ScaleZeroQuarticChamberRests3Scratch
import Grok810ScaleZeroQuarticChamberKills3Scratch
import Grok810ScaleZeroQuarticChamberRests4Scratch
import Grok810ScaleZeroQuarticChamberInnerScratch
import Grok810ScaleZeroQuarticChamberKills4Scratch
import Grok810ScaleZeroQuarticChamberColumns5Scratch
import Grok810ScaleZeroQuarticChamberRests5Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsScratch
import Grok810ScaleZeroQuarticChamberRests6Scratch
import Grok810ScaleZeroQuarticChamberInfraN2Scratch
import Grok810ScaleZeroQuarticChamberInfraN3Scratch
import Grok810ScaleZeroQuarticChamberInfraN4Scratch
import Grok810ScaleZeroQuarticChamberInfraN5Scratch
import Grok810ScaleZeroQuarticChamberInfraN6Scratch
import Grok810ScaleZeroQuarticChamberInfraN7Scratch
import Grok810ScaleZeroQuarticChamberInfraOmicronScratch
import Grok810ScaleZeroQuarticChamberInfraPrimitiveScratch
import Grok810ScaleZeroQuarticChamberN5CostLadderScratch
import Grok810ScaleZeroQuarticChamberN7BandsScratch
import Grok810ScaleZeroQuarticChamberUnownedPacketsScratch
import Grok810ScaleZeroQuarticChamberUnownedColumns1Scratch
import Grok810ScaleZeroQuarticChamberUnownedColumns2Scratch
import Grok810ScaleZeroQuarticChamberUnownedColumns3Scratch
import Grok810ScaleZeroQuarticChamberUnownedColumns4Scratch
import Grok810ScaleZeroQuarticChamberUnownedColumns5Scratch
import Grok810ScaleZeroQuarticChamberUnownedRests1Scratch
import Grok810ScaleZeroQuarticChamberUnownedRests2Scratch
import Grok810ScaleZeroQuarticChamberUnownedRests3Scratch
import Grok810ScaleZeroQuarticChamberUnownedRests4Scratch
import Grok810ScaleZeroQuarticChamberUnownedKills1Scratch
import Grok810ScaleZeroQuarticChamberUnownedKills2Scratch
import Grok810ScaleZeroQuarticChamberUnownedKills3Scratch
import Grok810ScaleZeroQuarticChamberUnownedKills4Scratch
import Grok810ScaleZeroQuarticChamberUnownedKills5Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemPackets1Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemPackets2Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemColumns1Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemColumns2Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemColumns3Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemColumns4Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemColumns5Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemColumns6Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemColumns7Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemColumns8Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemColumns9Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemColumns10Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemRests1Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemRests2Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemRests3Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemRests4Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemRests5Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemRests6Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemRests7Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemRests8Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemRests9Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemRests10Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemRests11Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemBridges1Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystemBridges2Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystems1Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystems2Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystems3Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystems4Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystems5Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystems6Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystems7Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystems8Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystems9Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystems10Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystems11Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystems12Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystems13Scratch
import Grok810ScaleZeroQuarticChamberUnownedSystems14Scratch
import Grok810ScaleZeroQuarticChamberUnownedSplitPacketsScratch
import Grok810ScaleZeroQuarticChamberUnownedSplitColumns1Scratch
import Grok810ScaleZeroQuarticChamberUnownedSplitRests1Scratch
import Grok810ScaleZeroQuarticChamberUnownedSplitsScratch
import Grok810ScaleZeroQuarticChamberUnownedRefinePacketsScratch
import Grok810ScaleZeroQuarticChamberUnownedRefineColumns1Scratch
import Grok810ScaleZeroQuarticChamberUnownedRefineRests1Scratch
import Grok810ScaleZeroQuarticChamberUnownedRefineScratch
import Grok810ScaleZeroQuarticChamberUnownedTreePackets1Scratch
import Grok810ScaleZeroQuarticChamberUnownedTreePackets2Scratch
import Grok810ScaleZeroQuarticChamberUnownedTreeColumns1Scratch
import Grok810ScaleZeroQuarticChamberUnownedTreeColumns2Scratch
import Grok810ScaleZeroQuarticChamberUnownedTreeColumns3Scratch
import Grok810ScaleZeroQuarticChamberUnownedTreeColumns4Scratch
import Grok810ScaleZeroQuarticChamberUnownedTreeRests1Scratch
import Grok810ScaleZeroQuarticChamberUnownedTreeRests2Scratch
import Grok810ScaleZeroQuarticChamberUnownedTreeRests3Scratch
import Grok810ScaleZeroQuarticChamberUnownedTreeRests4Scratch
import Grok810ScaleZeroQuarticChamberUnownedTreePiecesScratch
import Grok810ScaleZeroQuarticChamberUnownedTreeCertsScratch
import Grok810ScaleZeroQuarticChamberUnownedTrees1Scratch
import Grok810ScaleZeroQuarticChamberUnownedTrees2Scratch
import Grok810ScaleZeroQuarticChamberUnownedTrees3Scratch
import Grok810ScaleZeroQuarticChamberUnownedTrees4Scratch
import Grok810ScaleZeroQuarticChamberTowerPackets1Scratch
import Grok810ScaleZeroQuarticChamberTowerPackets2Scratch
import Grok810ScaleZeroQuarticChamberTowerColumns1Scratch
import Grok810ScaleZeroQuarticChamberTowerRests1Scratch
import Grok810ScaleZeroQuarticChamberTowerRests2Scratch
import Grok810ScaleZeroQuarticChamberTowerRests3Scratch
import Grok810ScaleZeroQuarticChamberTowerRests4Scratch
import Grok810ScaleZeroQuarticChamberTowerBridgesScratch
import Grok810ScaleZeroQuarticTowerScratch
import Grok810ScaleZeroQuarticChamberTowerKills2Part0Scratch
import Grok810ScaleZeroQuarticChamberTowerKills2Part101Scratch
import Grok810ScaleZeroQuarticChamberTowerKills2Part4Scratch

/-! # Tower deep-rescue chamber kills, part 2/4

5 of the 17 chambers `Grok810ScaleZeroQuarticTowerScratch` owns: the bridges of
`…ChamberTowerBridgesScratch` feed the tower's own scalar
`quarticCostChamber<tag>810_impossible`.  Every face is checked to be
the tower's face (exactly, up to the recorded rational scale) and every
load column carries a Farkas certificate.  Untracked working note.
-/

open scoped Polynomial.Bivariate

noncomputable section

open Polynomial

namespace Max11DegreeRoutes

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.unnecessarySeqFocus false
set_option linter.flexible false
set_option linter.style.haveILetI false
set_option linter.unnecessarySimpa false

set_option maxRecDepth 1000000

variable {k : Type*} [Field k] [CharZero k]

section QuarticChamberTowerKills2810

end QuarticChamberTowerKills2810

end Max11DegreeRoutes
