import Sol610ScaleTwoDegreeZeroPrimitivePart01Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart02Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart03Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart04Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart05Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart06Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart07Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart08Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart09Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart10Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart11Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart12Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart13Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart14Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart15Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart16Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart17Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart18Scratch
import Sol610ScaleTwoDegreeZeroPrimitivePart19Scratch

/-! # Exact primitive for the `(6,10)` degree-zero row

The last Jacobian row is inhomogeneous, so this weight-fifteen primitive is
not a first integral.  Its derivative is the literal row zero, modulo the
already established residual tower.  The grouped formula and differential
certificate were independently reconstructed by
`derive_610_degree_zero_residual.py` (SHA256
`cd333da32d89eb7eb86f0fc1043ee718f65716faa41edcf29bc4ca2248473b58`).
-/

namespace Max11DegreeRoutes

#print axioms degreeZeroPrimitive610_deriv_identity
#print axioms degreeZeroPrimitive610_deriv_eq_row

end Max11DegreeRoutes
