import Sol68LaterDeepLowerParentFiveToSixOffsetOneEightyOrdinaryI3TwoScratch

/-! # Ordinary offset-180: row-one coefficient four is a shadow

The complementary I3 lane left one exact lower-jet scalar at contracted
coefficient `2` (expanded `120`).  Here we consume contracted row-one
coefficient `4` (expanded `299`).  After its literal I3 loads cancel, the
row is the six-term edge core displayed below.  That core is already in the
ideal generated by the face, discriminant, cusp pin and three joined first
jets, so this row is derivative-dependent and gives no new scalar.  The I3
coefficient-`2` residual is retained verbatim.  The next unused complementary
source row is row-two coefficient `4` (expanded `299`).
-/

noncomputable section

open Polynomial

namespace Max11DegreeRoutes

section LaterDeepLowerParentFiveToSixOffsetOneEightyOrdinaryRowOneFour68

variable {k : Type*} [Field k] [CharZero k]

set_option maxHeartbeats 20000000
set_option maxRecDepth 10000
set_option linter.unusedSectionVars false
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false

/-- Homogeneous row-one coefficient `4`, expressed through the three
remaining I3 jets. -/
theorem secondaryResidualRowOnePolynomial68_coeff_four_ordinaryOneEighty68
    (A B c d e : k[X])
    (hA : A.natDegree ≤ 4) (hB : B.natDegree ≤ 0)
    (hc : c.natDegree ≤ 2) (hd : d.natDegree ≤ 1)
    (he : e.natDegree ≤ 3)
    (hthree5 :
      (secondaryResidualInvariantThreePolynomial68 A B c d e).coeff 5 = 0)
    (hthree4 :
      (secondaryResidualInvariantThreePolynomial68 A B c d e).coeff 4 = 0) :
    let J := secondaryResidualInvariantThreePolynomial68 A B c d e
    (secondaryResidualRowOnePolynomial68 A B c d e).coeff 4 =
      (1 / 27 : k) *
        (27 * A.coeff 2 * J.coeff 3 + 18 * A.coeff 3 * J.coeff 2 +
          40 * A.coeff 3 * B.coeff 0 ^ 2 * c.coeff 2 -
          60 * A.coeff 3 * d.coeff 1 ^ 2 +
          9 * A.coeff 4 * J.coeff 1 +
          40 * A.coeff 4 * B.coeff 0 ^ 2 * c.coeff 1 -
          120 * A.coeff 4 * d.coeff 0 * d.coeff 1 -
          120 * c.coeff 1 * c.coeff 2 ^ 2 +
          360 * e.coeff 2 * e.coeff 3) := by
  let J : k[X] := secondaryResidualInvariantThreePolynomial68 A B c d e
  let S : k[X] := fiveToSixRowOneS68 A B c d e
  dsimp only
  change (secondaryResidualRowOnePolynomial68 A B c d e).coeff 4 = _
  have hJdeg : J.natDegree ≤ 5 := by
    simp only [J, secondaryResidualInvariantThreePolynomial68]
    compute_degree
    omega
  have hJ3deg : J.natDegree ≤ 3 :=
    Polynomial.natDegree_le_iff_coeff_eq_zero.mpr (by
      intro n hn
      by_cases hn4 : n = 4
      · simpa only [J, hn4] using hthree4
      by_cases hn5 : n = 5
      · simpa only [J, hn5] using hthree5
      · exact coeff_eq_zero_of_natDegree_lt (hJdeg.trans_lt (by omega)))
  have hSJ := fiveToSixRowOne_S_I3_identity68 A B c d e
  change (2 : k) • S + (9 / 4 : k) • J =
      (3 : k) • d ^ 2 - (2 : k) • (B ^ 2 * c) at hSJ
  have hSsolve : S = (1 / 2 : k) •
      ((3 : k) • d ^ 2 - (2 : k) • (B ^ 2 * c) -
        (9 / 4 : k) • J) := by
    have h2S : (2 : k) • S =
        (3 : k) • d ^ 2 - (2 : k) • (B ^ 2 * c) -
          (9 / 4 : k) • J := eq_sub_of_add_eq hSJ
    rw [← h2S]
    module
  have hSdeg : S.natDegree ≤ 3 := by
    rw [hSsolve]
    compute_degree
    omega
  have hS4 : S.coeff 4 = 0 :=
    coeff_eq_zero_of_natDegree_lt (hSdeg.trans_lt (by norm_num))
  have hS5 : S.coeff 5 = 0 :=
    coeff_eq_zero_of_natDegree_lt (hSdeg.trans_lt (by norm_num))
  have hA5 : A.coeff 5 = 0 :=
    coeff_eq_zero_of_natDegree_lt (hA.trans_lt (by norm_num))
  have hAS5 : (A * S).coeff 5 =
      A.coeff 2 * S.coeff 3 + A.coeff 3 * S.coeff 2 +
        A.coeff 4 * S.coeff 1 := by
    have h := mul_coeff_five_oneTwentyOrdinaryNonzeroNext68 A S
    rw [hS4, hS5, hA5] at h
    linear_combination h
  have hderAS : (derivative (A * S)).coeff 4 =
      5 * (A.coeff 2 * S.coeff 3 + A.coeff 3 * S.coeff 2 +
        A.coeff 4 * S.coeff 1) := by
    rw [coeff_derivative, hAS5]
    norm_num
    ring
  have hJ4 : J.coeff 4 = 0 := by simpa only [J] using hthree4
  have hderAJ : (derivative A * J).coeff 4 =
      2 * A.coeff 2 * J.coeff 3 + 3 * A.coeff 3 * J.coeff 2 +
        4 * A.coeff 4 * J.coeff 1 := by
    have h := mul_coeff_four_oneTwentyOrdinaryNonzeroNext68 (derivative A) J
    rw [hJ4] at h
    norm_num [coeff_derivative, hA5] at h
    linear_combination h
  have hd2 : d.coeff 2 = 0 :=
    coeff_eq_zero_of_natDegree_lt (hd.trans_lt (by norm_num))
  have hBC : B = C (B.coeff 0) := eq_C_of_natDegree_le_zero hB
  have hB2cPoly : B ^ 2 * c = c * C (B.coeff 0 ^ 2) := by
    conv_lhs => rw [hBC]
    rw [← C_pow]
    ring
  have hB2c1 : (B ^ 2 * c).coeff 1 =
      B.coeff 0 ^ 2 * c.coeff 1 := by
    rw [hB2cPoly, coeff_mul_C]
    ring
  have hB2c2 : (B ^ 2 * c).coeff 2 =
      B.coeff 0 ^ 2 * c.coeff 2 := by
    rw [hB2cPoly, coeff_mul_C]
    ring
  have hdSq1 : (d ^ 2).coeff 1 = 2 * d.coeff 0 * d.coeff 1 := by
    rw [pow_two, mul_coeff_one]
    ring
  have hdSq2 : (d ^ 2).coeff 2 = d.coeff 1 ^ 2 := by
    rw [pow_two, mul_coeff_two68, hd2]
    ring
  have hright3 :
      ((3 : k) • d ^ 2 - (2 : k) • (B ^ 2 * c)).coeff 3 = 0 :=
    coeff_eq_zero_of_natDegree_lt (by compute_degree; omega)
  have hSJ1 := congrArg (fun p : k[X] => p.coeff 1) hSJ
  norm_num [coeff_add, coeff_sub, coeff_smul, smul_eq_mul, hdSq1, hB2c1]
    at hSJ1
  have hSJ2 := congrArg (fun p : k[X] => p.coeff 2) hSJ
  norm_num [coeff_add, coeff_sub, coeff_smul, smul_eq_mul, hdSq2, hB2c2]
    at hSJ2
  have hSJ3 := congrArg (fun p : k[X] => p.coeff 3) hSJ
  norm_num [coeff_add, coeff_sub, coeff_smul, smul_eq_mul, hright3] at hSJ3
  have hS1 : S.coeff 1 = 3 * d.coeff 0 * d.coeff 1 -
      B.coeff 0 ^ 2 * c.coeff 1 - (9 / 8 : k) * J.coeff 1 := by
    linear_combination (1 / 2 : k) * hSJ1
  have hS2 : S.coeff 2 = (3 / 2 : k) * d.coeff 1 ^ 2 -
      B.coeff 0 ^ 2 * c.coeff 2 - (9 / 8 : k) * J.coeff 2 := by
    linear_combination (1 / 2 : k) * hSJ2
  have hS3 : S.coeff 3 = (-9 / 8 : k) * J.coeff 3 := by
    linear_combination (1 / 2 : k) * hSJ3
  have hcc : (c ^ 2 * derivative c).coeff 4 =
      5 * c.coeff 1 * c.coeff 2 ^ 2 := by
    have hc3 : c.coeff 3 = 0 :=
      coeff_eq_zero_of_natDegree_lt (hc.trans_lt (by norm_num))
    have hc4 : c.coeff 4 = 0 :=
      coeff_eq_zero_of_natDegree_lt (hc.trans_lt (by norm_num))
    have hc5 : c.coeff 5 = 0 :=
      coeff_eq_zero_of_natDegree_lt (hc.trans_lt (by norm_num))
    have hcsq3 : (c ^ 2).coeff 3 = 2 * c.coeff 1 * c.coeff 2 := by
      rw [pow_two, mul_coeff_three_oneTwentyOrdinaryNonzero68, hc3]
      ring
    have hcsq4 : (c ^ 2).coeff 4 = c.coeff 2 ^ 2 := by
      have h := coeff_mul_at_bounds68 c c 2 2 hc hc
      norm_num at h
      rw [pow_two]
      linear_combination h
    have h := mul_coeff_four_oneTwentyOrdinaryNonzeroNext68
      (c ^ 2) (derivative c)
    norm_num [coeff_derivative, hc3, hc4, hc5, hcsq3, hcsq4] at h
    linear_combination h
  have hee : (e * derivative e).coeff 4 =
      5 * e.coeff 2 * e.coeff 3 := by
    have he4 : e.coeff 4 = 0 :=
      coeff_eq_zero_of_natDegree_lt (he.trans_lt (by norm_num))
    have he5 : e.coeff 5 = 0 :=
      coeff_eq_zero_of_natDegree_lt (he.trans_lt (by norm_num))
    have h := mul_coeff_four_oneTwentyOrdinaryNonzeroNext68 e (derivative e)
    norm_num [coeff_derivative, he4, he5] at h
    linear_combination h
  have hderB : derivative B = 0 := derivative_eq_zero.mpr (by omega)
  have hlow1 : (derivative (B * c * d)).natDegree < 4 := by
    rw [derivative_mul, derivative_mul, hderB]
    simp only [zero_mul, zero_add]
    compute_degree
    omega
  have hlow2 : (derivative B * c * d).natDegree < 4 := by
    rw [hderB, zero_mul, zero_mul, natDegree_zero]
    norm_num
  have hlow3 : (B ^ 2 * derivative e).natDegree < 4 := by
    compute_degree
    omega
  rw [fiveToSixRowOne_eq_inner68, coeff_smul]
  simp only [fiveToSixRowOneInner68, J, S, coeff_add, coeff_sub,
    coeff_smul, smul_eq_mul, hderAS, hderAJ, hS1, hS2, hS3, hcc, hee,
    coeff_eq_zero_of_natDegree_lt hlow1,
    coeff_eq_zero_of_natDegree_lt hlow2,
    coeff_eq_zero_of_natDegree_lt hlow3]
  ring

/-- Exact literal row-one load at coefficient `4`. -/
theorem cubicLoadRowOnePolynomial68_coeff_four_ordinaryOneEighty68
    (alpha gamma epsilon zeta eta : k) (A B c d e : k[X])
    (hA : A.natDegree ≤ 4) (hB : B.natDegree ≤ 0)
    (hc : c.natDegree ≤ 2) (hd : d.natDegree ≤ 1)
    (he : e.natDegree ≤ 3) :
    (cubicLoadRowOnePolynomial68 0 alpha 0 gamma 0 epsilon zeta eta
      A B c ((1 / 3 : k) • (A * B) + d) e).coeff 4 =
      4 * gamma * A.coeff 2 * e.coeff 3 +
        (8 / 3 : k) * gamma * A.coeff 3 * e.coeff 2 +
        (4 / 3 : k) * gamma * A.coeff 4 * e.coeff 1 +
        (4 / 3 : k) * epsilon * A.coeff 3 * c.coeff 2 +
        (2 / 3 : k) * epsilon * A.coeff 4 * c.coeff 1 := by
  let D0 : k[X] := (1 / 3 : k) • (A * B) + d
  let Ur : k[X] := (2 / 3 * gamma : k) • B + C zeta
  have hloadEq :
      cubicLoadRowOnePolynomial68 0 alpha 0 gamma 0 epsilon zeta eta
        A B c D0 e =
      Ur * derivative D0 +
        (4 / 3 * gamma : k) • (A * derivative e - c * derivative c) +
        (2 / 3 * epsilon : k) • (A * derivative c) +
        (2 * epsilon : k) • derivative e -
        (2 / 3 * gamma : k) • (D0 * derivative B) := by
    apply (FaithfulSMul.algebraMap_injective k[X] (RatFunc k))
    simp only [cubicLoadRowOnePolynomial68, cubicLoadTPolynomial68,
      cubicLoadUPolynomial68, cubicLoadVPolynomial68, D0, Ur,
      zero_mul, zero_smul, smul_zero, add_zero, zero_add, sub_zero,
      derivative_add, derivative_sub, derivative_mul, derivative_pow,
      derivative_smul, derivative_C, one_mul, Polynomial.smul_eq_C_mul,
      map_add, map_sub, map_mul, map_pow, map_neg, map_zero,
      RatFunc.algebraMap_C, map_div₀, map_ofNat, map_natCast, map_one]
    ring
  have hD : D0.natDegree ≤ 4 := by simp only [D0]; compute_degree; omega
  have hUr : Ur.natDegree ≤ 0 := by simp only [Ur]; compute_degree; omega
  have hlow1 : (Ur * derivative D0).natDegree < 4 := by
    compute_degree
    omega
  have hAe : (A * derivative e).coeff 4 =
      3 * A.coeff 2 * e.coeff 3 + 2 * A.coeff 3 * e.coeff 2 +
        A.coeff 4 * e.coeff 1 := by
    have hA5 : A.coeff 5 = 0 :=
      coeff_eq_zero_of_natDegree_lt (hA.trans_lt (by norm_num))
    have he4 : e.coeff 4 = 0 :=
      coeff_eq_zero_of_natDegree_lt (he.trans_lt (by norm_num))
    have he5 : e.coeff 5 = 0 :=
      coeff_eq_zero_of_natDegree_lt (he.trans_lt (by norm_num))
    have h := mul_coeff_four_oneTwentyOrdinaryNonzeroNext68 A (derivative e)
    norm_num [coeff_derivative, hA5, he4, he5] at h
    linear_combination h
  have hAc : (A * derivative c).coeff 4 =
      2 * A.coeff 3 * c.coeff 2 + A.coeff 4 * c.coeff 1 := by
    have hA5 : A.coeff 5 = 0 :=
      coeff_eq_zero_of_natDegree_lt (hA.trans_lt (by norm_num))
    have hc3 : c.coeff 3 = 0 :=
      coeff_eq_zero_of_natDegree_lt (hc.trans_lt (by norm_num))
    have hc4 : c.coeff 4 = 0 :=
      coeff_eq_zero_of_natDegree_lt (hc.trans_lt (by norm_num))
    have hc5 : c.coeff 5 = 0 :=
      coeff_eq_zero_of_natDegree_lt (hc.trans_lt (by norm_num))
    have h := mul_coeff_four_oneTwentyOrdinaryNonzeroNext68 A (derivative c)
    norm_num [coeff_derivative, hA5, hc3, hc4, hc5] at h
    linear_combination h
  have hlowc : (c * derivative c).natDegree < 4 := by compute_degree; omega
  have hlowe : (derivative e).natDegree < 4 := by compute_degree; omega
  have hderB : derivative B = 0 := derivative_eq_zero.mpr (by omega)
  change (cubicLoadRowOnePolynomial68 0 alpha 0 gamma 0 epsilon zeta eta
      A B c D0 e).coeff 4 = _
  rw [hloadEq]
  simp only [hderB, mul_zero, zero_smul, sub_zero, coeff_add, coeff_sub,
    coeff_smul, coeff_zero, smul_eq_mul, hAe, hAc,
    coeff_eq_zero_of_natDegree_lt hlow1,
    coeff_eq_zero_of_natDegree_lt hlowc,
    coeff_eq_zero_of_natDegree_lt hlowe]
  ring

/-- Cancellation of the literal I3 loads in row-one coefficient `4`. -/
theorem fiveToSix_ordinaryOneEighty_rowOneFour_reduced68
    (a₂ a₃ a₄ b c₁ c₂ d₀ d₁ e₁ e₂ e₃ gamma epsilon
      J₁ J₂ J₃ : k)
    (hJ1 : J₁ + 2 * epsilon * c₁ + 4 * gamma * e₁ = 0)
    (hJ2 : J₂ + 2 * epsilon * c₂ + 4 * gamma * e₂ = 0)
    (hJ3 : J₃ + 4 * gamma * e₃ = 0)
    (hrow : (1 / 27 : k) *
        (27 * a₂ * J₃ + 18 * a₃ * J₂ + 40 * a₃ * b ^ 2 * c₂ -
          60 * a₃ * d₁ ^ 2 + 9 * a₄ * J₁ + 40 * a₄ * b ^ 2 * c₁ -
          120 * a₄ * d₀ * d₁ - 120 * c₁ * c₂ ^ 2 +
          360 * e₂ * e₃) +
        4 * gamma * a₂ * e₃ + (8 / 3 : k) * gamma * a₃ * e₂ +
        (4 / 3 : k) * gamma * a₄ * e₁ +
        (4 / 3 : k) * epsilon * a₃ * c₂ +
        (2 / 3 : k) * epsilon * a₄ * c₁ = 0) :
    2 * a₃ * b ^ 2 * c₂ - 3 * a₃ * d₁ ^ 2 +
      2 * a₄ * b ^ 2 * c₁ - 6 * a₄ * d₀ * d₁ -
      6 * c₁ * c₂ ^ 2 + 18 * e₂ * e₃ = 0 := by
  linear_combination (27 / 20 : k) * hrow -
    (27 / 20 : k) * a₂ * hJ3 -
    (9 / 10 : k) * a₃ * hJ2 -
    (9 / 20 : k) * a₄ * hJ1

/-- The reduced row-one core is already generated by the joined edge
relations. -/
theorem fiveToSix_ordinaryOneEighty_rowOneFour_shadow68
    (a a₃ b c₁ c₂ d₀ d₁ e₂ e₃ : k)
    (hb : b ≠ 0) (hcTop : c₂ ≠ 0)
    (hface : b * e₃ + c₂ * d₁ = 0)
    (hdisc : a * b ^ 2 + 3 * c₂ ^ 2 = 0)
    (hedge : 9 * e₃ ^ 2 - 4 * c₂ ^ 3 = 0)
    (hT1 : a₃ * b ^ 2 + 6 * c₁ * c₂ = 0)
    (hT2 : 2 * c₂ * d₀ - c₁ * d₁ = 0)
    (hT3 : 2 * b * e₂ + 3 * c₁ * d₁ = 0) :
    2 * a₃ * b ^ 2 * c₂ - 3 * a₃ * d₁ ^ 2 +
      2 * a * b ^ 2 * c₁ - 6 * a * d₀ * d₁ -
      6 * c₁ * c₂ ^ 2 + 18 * e₂ * e₃ = 0 := by
  have hpins : c₂ ^ 2 * (4 * b ^ 2 * c₂ - 9 * d₁ ^ 2) = 0 := by
    linear_combination (-(b ^ 2)) * hedge +
      (9 * (b * e₃ - c₂ * d₁)) * hface
  have hpin : 4 * b ^ 2 * c₂ - 9 * d₁ ^ 2 = 0 :=
    (mul_eq_zero.mp hpins).resolve_left (pow_ne_zero 2 hcTop)
  have hscaled : b ^ 2 * c₂ *
      (2 * a₃ * b ^ 2 * c₂ - 3 * a₃ * d₁ ^ 2 +
        2 * a * b ^ 2 * c₁ - 6 * a * d₀ * d₁ -
        6 * c₁ * c₂ ^ 2 + 18 * e₂ * e₃) = 0 := by
    linear_combination
      (-2 * b ^ 2 * c₂ ^ 2 - 6 * b * d₁ * e₃) * hT1 +
      (2 * b ^ 2 * c₂ * c₁ + 6 * b * d₀ * e₃) * hdisc -
      (9 * b * c₂ * e₃) * hT2 +
      (9 * b * c₂ * e₃) * hT3 +
      (-6 * a * b ^ 2 * d₀ + 6 * a₃ * b ^ 2 * d₁) * hface +
      (a₃ * b ^ 2 * c₂) * hpin
  have hb2 : b ^ 2 ≠ 0 := pow_ne_zero 2 hb
  have hbc : b ^ 2 * c₂ ≠ 0 := mul_ne_zero hb2 hcTop
  exact (mul_eq_zero.mp hscaled).resolve_left hbc

set_option maxHeartbeats 15000000 in
/-- Source-facing successor packet.  It extracts row-one coefficient `4`
with its literal load, proves that coefficient is an incidence shadow, and
retains the independent I3 coefficient-`2` scalar exactly. -/
theorem fiveToSix_offsetOneEighty_ordinary_rowOneFour_source_packet68
    (alpha gamma epsilon eta i4 i3 : k) (A B c d e : k[X])
    (hA : A.natDegree ≤ 4) (hB : B.natDegree ≤ 0)
    (hc : c.natDegree ≤ 2) (hd : d.natDegree ≤ 1)
    (he : e.natDegree ≤ 3)
    (hb : B.coeff 0 ≠ 0) (hcTop : c.coeff 2 ≠ 0)
    (hface : B.coeff 0 * e.coeff 3 + c.coeff 2 * d.coeff 1 = 0)
    (hdisc : A.coeff 4 * B.coeff 0 ^ 2 + 3 * c.coeff 2 ^ 2 = 0)
    (hi4rigid : 27 * A.coeff 4 * i4 + 32 * A.coeff 4 * B.coeff 0 ^ 3 +
      216 * d.coeff 1 * e.coeff 3 = 0)
    (hedge : 9 * e.coeff 3 ^ 2 - 4 * c.coeff 2 ^ 3 = 0)
    (hjetDisc : A.coeff 3 * B.coeff 0 ^ 2 +
      6 * c.coeff 1 * c.coeff 2 = 0)
    (hjetEdge : 2 * c.coeff 2 * d.coeff 0 -
      c.coeff 1 * d.coeff 1 = 0)
    (hjetLoad : 2 * B.coeff 0 * e.coeff 2 +
      3 * c.coeff 1 * d.coeff 1 = 0)
    (hgain : 2 * c.coeff 1 ^ 2 -
      c.coeff 2 * (8 * c.coeff 0 + 21 * gamma) = 0)
    (hi3 : cubicFirstIntegralThreePolynomial68 0 0 gamma 0 epsilon 0
      A B c ((1 / 3 : k) • (A * B) + d) e = C i3)
    (hrowOne :
      let C0 := (1 / 3 : k) • A ^ 2 + c
      let D0 := (1 / 3 : k) • (A * B) + d
      let E0 := (1 / 27 : k) • A ^ 3 + (1 / 3 : k) • (A * c) + e
      (lowerRowOnePolynomial68
        (integratedTPolynomial68 0 alpha 0 gamma epsilon A B C0 D0 E0)
        (integratedUPolynomial68 0 alpha 0 gamma 0 0 A B C0 D0 E0)
        (integratedVPolynomial68 0 alpha 0 gamma 0 epsilon eta
          A B C0 D0 E0) C0 D0 E0).coeff 4 = 0) :
    (27 * A.coeff 4 * i4 + 32 * A.coeff 4 * B.coeff 0 ^ 3 +
        216 * d.coeff 1 * e.coeff 3 = 0) ∧
      (9 * e.coeff 3 ^ 2 - 4 * c.coeff 2 ^ 3 = 0) ∧
      (A.coeff 3 * B.coeff 0 ^ 2 + 6 * c.coeff 1 * c.coeff 2 = 0) ∧
      (2 * c.coeff 2 * d.coeff 0 - c.coeff 1 * d.coeff 1 = 0) ∧
      (2 * B.coeff 0 * e.coeff 2 + 3 * c.coeff 1 * d.coeff 1 = 0) ∧
      (2 * c.coeff 1 ^ 2 -
        c.coeff 2 * (8 * c.coeff 0 + 21 * gamma) = 0) ∧
      (84 * A.coeff 1 * B.coeff 0 ^ 2 * c.coeff 2 * d.coeff 1 +
        42 * A.coeff 2 * B.coeff 0 ^ 2 * c.coeff 1 * d.coeff 1 +
        28 * B.coeff 0 ^ 3 * c.coeff 2 ^ 2 -
        252 * B.coeff 0 * c.coeff 2 ^ 2 * e.coeff 0 -
        189 * B.coeff 0 * c.coeff 2 ^ 2 * epsilon -
        252 * B.coeff 0 * c.coeff 2 * c.coeff 1 * e.coeff 1 +
        162 * c.coeff 2 * c.coeff 0 * c.coeff 1 * d.coeff 1 +
        54 * c.coeff 1 ^ 3 * d.coeff 1 = 0) ∧
      (2 * A.coeff 3 * B.coeff 0 ^ 2 * c.coeff 2 -
        3 * A.coeff 3 * d.coeff 1 ^ 2 +
        2 * A.coeff 4 * B.coeff 0 ^ 2 * c.coeff 1 -
        6 * A.coeff 4 * d.coeff 0 * d.coeff 1 -
        6 * c.coeff 1 * c.coeff 2 ^ 2 +
        18 * e.coeff 2 * e.coeff 3 = 0) := by
  let J : k[X] := secondaryResidualInvariantThreePolynomial68 A B c d e
  have hI3J : J + (2 * epsilon : k) • c + (4 * gamma : k) • e -
      (2 / 3 * gamma : k) • B ^ 2 = C i3 := by
    have hres := hi3
    rw [cubicFirstIntegralThreePolynomial68_fiveToSix_residualCoordinates]
      at hres
    simp only [zero_smul, zero_add] at hres
    simpa only [J, add_zero] using hres
  have hB2deg : (B ^ 2).natDegree ≤ 0 := by compute_degree; omega
  have hB2pos : ∀ j, 0 < j → (B ^ 2).coeff j = 0 := by
    intro j hj
    exact coeff_eq_zero_of_natDegree_lt (hB2deg.trans_lt hj)
  have hc3 : c.coeff 3 = 0 :=
    coeff_eq_zero_of_natDegree_lt (hc.trans_lt (by norm_num))
  have hc4 : c.coeff 4 = 0 :=
    coeff_eq_zero_of_natDegree_lt (hc.trans_lt (by norm_num))
  have hc5 : c.coeff 5 = 0 :=
    coeff_eq_zero_of_natDegree_lt (hc.trans_lt (by norm_num))
  have he4 : e.coeff 4 = 0 :=
    coeff_eq_zero_of_natDegree_lt (he.trans_lt (by norm_num))
  have he5 : e.coeff 5 = 0 :=
    coeff_eq_zero_of_natDegree_lt (he.trans_lt (by norm_num))
  have h5 := congrArg (fun p : k[X] => p.coeff 5) hI3J
  norm_num [coeff_add, coeff_sub, coeff_smul, smul_eq_mul, coeff_C,
    hc5, he5, hB2pos 5 (by norm_num)] at h5
  have hJ5 : J.coeff 5 = 0 := h5
  have h4 := congrArg (fun p : k[X] => p.coeff 4) hI3J
  norm_num [coeff_add, coeff_sub, coeff_smul, smul_eq_mul, coeff_C,
    hc4, he4, hB2pos 4 (by norm_num)] at h4
  have hJ4 : J.coeff 4 = 0 := h4
  have h3 := congrArg (fun p : k[X] => p.coeff 3) hI3J
  norm_num [coeff_add, coeff_sub, coeff_smul, smul_eq_mul, coeff_C,
    hc3, hB2pos 3 (by norm_num)] at h3
  have hJ3 : J.coeff 3 + 4 * gamma * e.coeff 3 = 0 := by
    linear_combination h3
  have h2 := congrArg (fun p : k[X] => p.coeff 2) hI3J
  norm_num [coeff_add, coeff_sub, coeff_smul, smul_eq_mul, coeff_C,
    hB2pos 2 (by norm_num)] at h2
  have hJ2 : J.coeff 2 + 2 * epsilon * c.coeff 2 +
      4 * gamma * e.coeff 2 = 0 := by
    linear_combination h2
  have h1 := congrArg (fun p : k[X] => p.coeff 1) hI3J
  norm_num [coeff_add, coeff_sub, coeff_smul, smul_eq_mul, coeff_C,
    hB2pos 1 (by norm_num)] at h1
  have hJ1 : J.coeff 1 + 2 * epsilon * c.coeff 1 +
      4 * gamma * e.coeff 1 = 0 := by
    linear_combination h1
  let C0 : k[X] := (1 / 3 : k) • A ^ 2 + c
  let D0 : k[X] := (1 / 3 : k) • (A * B) + d
  let E0 : k[X] :=
    (1 / 27 : k) • A ^ 3 + (1 / 3 : k) • (A * c) + e
  change (lowerRowOnePolynomial68
      (integratedTPolynomial68 0 alpha 0 gamma epsilon A B C0 D0 E0)
      (integratedUPolynomial68 0 alpha 0 gamma 0 0 A B C0 D0 E0)
      (integratedVPolynomial68 0 alpha 0 gamma 0 epsilon eta
        A B C0 D0 E0) C0 D0 E0).coeff 4 = 0 at hrowOne
  have hcoords := integratedPolynomial68_cubicCoordinates
    (0 : k) alpha 0 gamma 0 epsilon 0 eta A B c D0 e
  have hhom : cubicHomogeneousRowOnePolynomial68 A B c D0 e =
      secondaryResidualRowOnePolynomial68 A B c d e := by
    simpa only [D0] using
      cubicHomogeneousRowOnePolynomial68_residualCoordinates A B c d e
  have hres :=
    secondaryResidualRowOnePolynomial68_coeff_four_ordinaryOneEighty68
      A B c d e hA hB hc hd he hJ5 hJ4
  have hload := cubicLoadRowOnePolynomial68_coeff_four_ordinaryOneEighty68
    alpha gamma epsilon 0 eta A B c d e hA hB hc hd he
  rw [hcoords.t_eq, hcoords.u_eq, hcoords.v_eq,
    cubicRowOnePolynomial68_split, coeff_add, hhom, hres, hload] at hrowOne
  have hcore := fiveToSix_ordinaryOneEighty_rowOneFour_reduced68
    (A.coeff 2) (A.coeff 3) (A.coeff 4) (B.coeff 0)
    (c.coeff 1) (c.coeff 2) (d.coeff 0) (d.coeff 1)
    (e.coeff 1) (e.coeff 2) (e.coeff 3) gamma epsilon
    (J.coeff 1) (J.coeff 2) (J.coeff 3) hJ1 hJ2 hJ3
    (by linear_combination hrowOne)
  have hi3packet :=
    fiveToSix_offsetOneEighty_ordinary_i3Two_source_packet68
      gamma epsilon i3 A B c d e hA hB hc hd he hb hcTop hface hedge
      hjetEdge hjetLoad hgain hi3
  refine ⟨hi4rigid, hedge, hjetDisc, hjetEdge, hjetLoad, hgain,
    hi3packet.2, ?_⟩
  exact hcore

#print axioms secondaryResidualRowOnePolynomial68_coeff_four_ordinaryOneEighty68
#print axioms cubicLoadRowOnePolynomial68_coeff_four_ordinaryOneEighty68
#print axioms fiveToSix_ordinaryOneEighty_rowOneFour_reduced68
#print axioms fiveToSix_ordinaryOneEighty_rowOneFour_shadow68
#print axioms fiveToSix_offsetOneEighty_ordinary_rowOneFour_source_packet68

end LaterDeepLowerParentFiveToSixOffsetOneEightyOrdinaryRowOneFour68

end Max11DegreeRoutes
