import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring

/-!  Tier-1 machine check for LEMMA.md (open_8_28_c2, generic chart).

Generated by cases/export_lean.py from the recorded Cascade3 event log
(cases/eq3_chain.py machinery).  Variables are named as in LEMMA.md:
`aN`/`bN` are the P/Q coefficient unknowns, `iaN` the formal localization
inverse of `aN`.
-/

/-- (A) the final substitution: the untouched vertex equation
`eq #3 = a1*b3 - 1` evaluates at `b3 = 0` to the unit `-1`.
A plain commutative-ring identity. -/
theorem eq3_at_b3_zero {K : Type*} [CommRing K] (a1 b3 : K) (h : b3 = 0) :
    a1*b3 - 1 = -1 := by subst h; ring

set_option linter.unusedVariables false in  -- hu1/hu2 stated, not consumed
/-- (B) the culprit reduction: the original key-(3,6) bracket coefficient,
after the 10 recorded collapse events (3 zeroings, 7 unit-pivot
eliminations, hypotheses `h1`..`h10` in chronological order), equals the
single monomial `(-1/5)*a2^2*a6*ia1^2*b3` in the localized ring of the
generic chart: `hu1`/`hu2` are the adjoined unit relations `ia1*a1 = 1`,
`ib43*b43 = 1` under which that ring lives.  The closing `ring` does not
in fact consume `hu1`/`hu2` — `a1` and `b43` never occur in the chain, so
the identity already holds in the free (polynomial) commutative ring,
which is strictly stronger and specializes to the localization
`Q[a,b][ia1,ib43]/(ia1*a1-1, ib43*b43-1)` of LEMMA.md.  Stated over a
field of characteristic 0 so the literal rational coefficients elaborate;
the denominators are exactly the pivot-constant primes {2,3,5} (LEMMA.md
denominator hygiene). -/
theorem culprit_key36_reduction {K : Type*} [Field K] [CharZero K]
    (a1 a2 a4 a5 a6 a8 a9 b3 b43 ia1 ib43
     b1 b2 b10 b9 b8 b7 b6 b5 b4 a3 : K)
    (hu1 : ia1*a1 = 1)
    (hu2 : ib43*b43 = 1)
    (h1 : b1 = 0)
    (h2 : b2 = 0)
    (h3 : b10 = (-1/3)*a2*b9*ia1 + (1/3)*a3*b8*ia1 + (-2/3)*a4*b6*ia1 + (2/3)*a6*b4*ia1)
    (h4 : b9 = (-1/5)*a2*b8*ia1 + (3/5)*a3*b7*ia1 + (-2/5)*a4*b5*ia1 + (2/5)*a5*b4*ia1 + (6/5)*a6*b3*ia1)
    (h5 : b8 = (1)*a5*b3*ia1)
    (h6 : b7 = (2/3)*a4*b3*ia1)
    (h7 : b6 = (-1/4)*a2*b5*ia1 + (1/2)*a3*b4*ia1)
    (h8 : b5 = (1)*a3*b3*ia1)
    (h9 : b4 = (1/2)*a2*b3*ia1)
    (h10 : a3 = 0)
    : (3)*a2*b10 + (-1)*a3*b9 + (2)*a5*b6 + (-2)*a6*b5 + (1)*a8*b2 + (-3)*a9*b1
      = (-1/5)*a2^2*a6*b3*ia1^2 := by
  subst h1 h2 h3 h4 h5 h6 h7 h8 h9 h10
  ring
