import Fable610ScaleZeroTenthDefectSpeedTPart01Scratch
import Fable610ScaleZeroTenthDefectSpeedTPart02Scratch
import Fable610ScaleZeroTenthDefectSpeedTPart03Scratch
import Fable610ScaleZeroTenthDefectSpeedTPart04Scratch
import Fable610ScaleZeroTenthDefectSpeedTPart05Scratch
import Fable610ScaleZeroTenthDefectSpeedTPart06Scratch

/-! Scale-zero tenth-defect packet in bounded modules.
Public statements and definition forms are preserved. -/
