import Grok810ScaleZeroQuarticChamberRests5Scratch
import Grok810ScaleZeroQuarticPowerCertificatesScratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart1Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart2Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart3Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart4Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart5Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart6Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart7Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart8Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart9Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart10Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart11Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart12Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart13Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart14Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart15Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart16Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart17Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart18Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart19Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart20Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart21Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart22Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart23Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart24Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart25Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart26Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart27Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart28Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart29Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart30Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart31Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart32Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart33Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart34Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart35Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart36Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart37Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart38Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart39Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart40Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart41Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart42Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart43Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart44Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart45Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart46Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart47Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart48Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart49Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart50Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart51Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart52Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart53Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart54Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart55Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart56Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart57Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart58Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart59Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart60Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart61Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart62Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart63Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart64Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart65Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart66Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart67Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart68Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart69Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart70Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart71Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart72Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart73Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart74Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart75Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart76Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart77Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart78Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart79Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart80Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart81Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart82Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart83Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart84Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart85Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart86Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart87Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart88Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart89Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart90Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart91Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart92Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart93Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart94Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart95Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart96Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart97Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart98Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart99Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart100Scratch
import Grok810ScaleZeroQuarticChamberPowerKillsPart101Scratch

/-! # Power-target chamber kills, `(8,10)` scale zero

42 top-coefficient bridges and 59 chamber kills against the
tracked, green `Grok810ScaleZeroQuarticPowerCertificatesScratch`
(SHA 102939dc): each carrier's face top coefficient is extracted, and
the Singular-lifted isobaric identity then forces a product of non-zero
leading coefficients to vanish.  Which chambers qualify is decided by
`scripts/derive_810_quartic_chamber_killplan5.py`.  Untracked note.
-/

open scoped Polynomial.Bivariate

noncomputable section

open Polynomial

namespace Max11DegreeRoutes

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.unnecessarySeqFocus false
set_option linter.flexible false
set_option linter.style.haveILetI false
set_option linter.unnecessarySimpa false

set_option maxRecDepth 1000000

variable {k : Type*} [Field k] [CharZero k]

section QuarticChamberPowerKills810

/-! ## Top-coefficient bridges to the power-target inner scalars -/

end QuarticChamberPowerKills810

end Max11DegreeRoutes
