import Grok810ScaleZeroQuarticChamberRests6Scratch
import Grok810ScaleZeroQuarticPowerCertificatesScratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart0Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart1Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart2Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart3Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart4Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart5Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart6Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart7Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart8Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart9Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart10Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart11Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart12Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart13Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart14Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart15Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart16Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart17Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart18Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart19Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart20Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart21Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart22Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart23Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart24Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart25Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart26Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart27Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart28Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart29Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart30Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart31Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart32Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart33Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart34Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart35Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart36Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart37Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart38Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart39Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart40Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart41Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart42Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart43Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart44Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart45Scratch
import Grok810ScaleZeroQuarticChamberRefinedKillsPart46Scratch

/-! # Refined-leaf kills, `(8,10)` scale zero

22 of the 59 leaves of the 11 carrier-refined cells: 8 on a
single-monomial face of some carrier, 17 on the power systems
`S24`-`S34` that `Grok810ScaleZeroQuarticPowerCertificatesScratch`
produced for exactly those cells.  The leaves come from the tournament
of `…ChamberRefineScratch`; their load columns are decided against the
leaf's *full* conjunct set (cell + refinement) in
`scripts/derive_810_quartic_chamber_killplan6.py`.  Untracked note.
-/

open scoped Polynomial.Bivariate

noncomputable section

open Polynomial

namespace Max11DegreeRoutes

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.unnecessarySeqFocus false
set_option linter.flexible false
set_option linter.style.haveILetI false
set_option linter.unnecessarySimpa false

set_option maxRecDepth 1000000

variable {k : Type*} [Field k] [CharZero k]

section QuarticChamberRefinedKills810

/-! ## Top-coefficient bridges for the refined leaves -/

end QuarticChamberRefinedKills810

end Max11DegreeRoutes
