import Sol68LaterDeepLowerParentFiveToSixOffsetOneEightyOrdinaryRowZeroScratch

/-! # Companion row-one packet at ordinary offset 180

Contracted row-one coefficient `5` is expanded index `359`.  It is the
first row-one coefficient not generated by the positive-degree I3 jets.
-/

noncomputable section

open Polynomial

namespace Max11DegreeRoutes

section LaterDeepLowerParentFiveToSixOffsetOneEightyOrdinaryRowOne68

variable {k : Type*} [Field k] [CharZero k]

set_option maxHeartbeats 30000000
set_option maxRecDepth 10000
set_option linter.unusedSectionVars false
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false

def fiveToSixRowOneS68 (A B c d e : k[X]) : k[X] :=
  A * B * d - (3 : k) • (c * e)

def fiveToSixRowOneInner68 (A B c d e : k[X]) : k[X] :=
  (2 : k) • derivative (A * fiveToSixRowOneS68 A B c d e) +
    (9 / 4 : k) •
      (derivative A * secondaryResidualInvariantThreePolynomial68 A B c d e) +
    (6 : k) • (c ^ 2 * derivative c) +
    (3 : k) • derivative (B * c * d) +
    (6 : k) • (derivative B * c * d) -
    (3 : k) • (B ^ 2 * derivative e) -
    (18 : k) • (e * derivative e)

theorem fiveToSixRowOne_S_I3_identity68 (A B c d e : k[X]) :
    (2 : k) • fiveToSixRowOneS68 A B c d e +
      (9 / 4 : k) • secondaryResidualInvariantThreePolynomial68 A B c d e =
      (3 : k) • d ^ 2 - (2 : k) • (B ^ 2 * c) := by
  apply (FaithfulSMul.algebraMap_injective k[X] (RatFunc k))
  simp only [fiveToSixRowOneS68, secondaryResidualInvariantThreePolynomial68,
    Polynomial.smul_eq_C_mul, map_add, map_sub, map_mul, map_pow, map_neg,
    RatFunc.algebraMap_C]
  simp only [map_div₀, map_ofNat, map_one]
  have hneg8 : RatFunc.C (-8 : k) = (-8 : RatFunc k) := by
    rw [show (-8 : k) = -(8 : k) by norm_num, map_neg, map_ofNat]
  rw [hneg8]
  ring

theorem fiveToSixRowOne_eq_inner68 (A B c d e : k[X]) :
    secondaryResidualRowOnePolynomial68 A B c d e =
      (-4 / 27 : k) • fiveToSixRowOneInner68 A B c d e := by
  simp only [secondaryResidualRowOnePolynomial68, fiveToSixRowOneInner68,
    fiveToSixRowOneS68, secondaryResidualInvariantThreePolynomial68,
    derivative_add, derivative_sub, derivative_mul, derivative_smul,
    derivative_pow, derivative_C, zero_mul, zero_add, smul_add, smul_sub,
    Polynomial.smul_eq_C_mul]
  apply (FaithfulSMul.algebraMap_injective k[X] (RatFunc k))
  simp only [map_add, map_sub, map_mul, map_pow, map_neg, map_zero,
    RatFunc.algebraMap_C, map_div₀, map_ofNat, map_natCast, map_one]
  ring

/-- Homogeneous row-one coefficient `5`, factored through the two remaining
I3 jets. -/
theorem secondaryResidualRowOnePolynomial68_coeff_five_ordinaryOneEighty68
    (A B c d e : k[X])
    (hA : A.natDegree ≤ 4) (hB : B.natDegree ≤ 0)
    (hc : c.natDegree ≤ 2) (hd : d.natDegree ≤ 1)
    (he : e.natDegree ≤ 3)
    (hthree5 :
      (secondaryResidualInvariantThreePolynomial68 A B c d e).coeff 5 = 0)
    (hthree4 :
      (secondaryResidualInvariantThreePolynomial68 A B c d e).coeff 4 = 0) :
    let J := secondaryResidualInvariantThreePolynomial68 A B c d e
    (secondaryResidualRowOnePolynomial68 A B c d e).coeff 5 =
      (2 / 3 : k) * A.coeff 4 * J.coeff 2 +
        A.coeff 3 * J.coeff 3 +
        (16 / 9 : k) * A.coeff 4 * B.coeff 0 ^ 2 * c.coeff 2 -
        (8 / 3 : k) * A.coeff 4 * d.coeff 1 ^ 2 -
        (16 / 9 : k) * c.coeff 2 ^ 3 +
        8 * e.coeff 3 ^ 2 := by
  let J : k[X] := secondaryResidualInvariantThreePolynomial68 A B c d e
  let S : k[X] := fiveToSixRowOneS68 A B c d e
  dsimp only
  change (secondaryResidualRowOnePolynomial68 A B c d e).coeff 5 = _
  have hderB : derivative B = 0 := derivative_eq_zero.mpr (by omega)
  have hJdeg : J.natDegree ≤ 5 := by
    simp only [J, secondaryResidualInvariantThreePolynomial68]
    compute_degree
    omega
  have hJ3 : J.natDegree ≤ 3 :=
    Polynomial.natDegree_le_iff_coeff_eq_zero.mpr (by
      intro n hn
      by_cases hn4 : n = 4
      · simpa only [J, hn4] using hthree4
      by_cases hn5 : n = 5
      · simpa only [J, hn5] using hthree5
      · exact coeff_eq_zero_of_natDegree_lt (hJdeg.trans_lt (by omega)))
  have hSJ := fiveToSixRowOne_S_I3_identity68 A B c d e
  change (2 : k) • S + (9 / 4 : k) • J =
      (3 : k) • d ^ 2 - (2 : k) • (B ^ 2 * c) at hSJ
  have hSsolve : S = (1 / 2 : k) •
      ((3 : k) • d ^ 2 - (2 : k) • (B ^ 2 * c) -
        (9 / 4 : k) • J) := by
    have h2S : (2 : k) • S =
        (3 : k) • d ^ 2 - (2 : k) • (B ^ 2 * c) -
          (9 / 4 : k) • J := eq_sub_of_add_eq hSJ
    rw [← h2S]
    module
  have hS3 : S.natDegree ≤ 3 := by
    rw [hSsolve]
    compute_degree
    omega
  have hASraw := congrArg (fun p : k[X] => p.coeff 1)
    (reflect_mul A S hA hS3)
  rw [mul_coeff_one] at hASraw
  norm_num [coeff_reflect] at hASraw
  have hAS6 : (A * S).coeff 6 =
      A.coeff 4 * S.coeff 2 + A.coeff 3 * S.coeff 3 := by
    linear_combination hASraw
  have hderAS : (derivative (A * S)).coeff 5 =
      6 * (A.coeff 4 * S.coeff 2 + A.coeff 3 * S.coeff 3) := by
    rw [coeff_derivative, hAS6]
    norm_num
    ring
  have hderA : (derivative A).natDegree ≤ 3 := by compute_degree; omega
  have hAJraw := congrArg (fun p : k[X] => p.coeff 1)
    (reflect_mul (derivative A) J hderA hJ3)
  rw [mul_coeff_one] at hAJraw
  norm_num [coeff_reflect, coeff_derivative] at hAJraw
  have hAJ5 : (derivative A * J).coeff 5 =
      4 * A.coeff 4 * J.coeff 2 + 3 * A.coeff 3 * J.coeff 3 := by
    linear_combination hAJraw
  have hB2deg : (B ^ 2).natDegree ≤ 0 := by compute_degree; omega
  have hB2top := coeff_pow_at_bound68 B 0 2 hB
  norm_num at hB2top
  have h2deg : (d ^ 2).natDegree ≤ 2 := by compute_degree; omega
  have hd2top := coeff_pow_at_bound68 d 1 2 hd
  norm_num at hd2top
  have hB2c2 := coeff_mul_at_bounds68 (B ^ 2) c 0 2 hB2deg hc
  norm_num [hB2top] at hB2c2
  have hSJ2 := congrArg (fun p : k[X] => p.coeff 2) hSJ
  norm_num [coeff_add, coeff_sub, coeff_smul, smul_eq_mul, hd2top,
    hB2c2] at hSJ2
  have hSJ3 := congrArg (fun p : k[X] => p.coeff 3) hSJ
  have hright3 : ((3 : k) • d ^ 2 - (2 : k) • (B ^ 2 * c)).coeff 3 = 0 :=
    coeff_eq_zero_of_natDegree_lt (by compute_degree; omega)
  norm_num [coeff_add, coeff_sub, coeff_smul, smul_eq_mul, hright3] at hSJ3
  have hc2deg : (c ^ 2).natDegree ≤ 4 := by compute_degree; omega
  have hc2top := coeff_pow_at_bound68 c 2 2 hc
  norm_num at hc2top
  have hcc := coeff_mul_at_bounds68 (c ^ 2) (derivative c) 4 1 hc2deg
    (by compute_degree; omega)
  norm_num [hc2top, coeff_derivative] at hcc
  have hee := coeff_mul_at_bounds68 e (derivative e) 3 2 he
    (by compute_degree; omega)
  norm_num [coeff_derivative] at hee
  have hlow1 : (derivative (B * c * d)).natDegree < 5 := by
    rw [derivative_mul, derivative_mul, hderB]
    simp only [zero_mul, zero_add]
    compute_degree
    omega
  have hlow2 : (derivative B * c * d).natDegree < 5 := by
    compute_degree; omega
  have hlow3 : (B ^ 2 * derivative e).natDegree < 5 := by
    compute_degree; omega
  rw [fiveToSixRowOne_eq_inner68, coeff_smul]
  simp only [fiveToSixRowOneInner68, J, S, coeff_add, coeff_sub,
    coeff_smul, smul_eq_mul, hderAS, hAJ5, hcc, hee,
    coeff_eq_zero_of_natDegree_lt hlow1,
    coeff_eq_zero_of_natDegree_lt hlow2,
    coeff_eq_zero_of_natDegree_lt hlow3]
  linear_combination (-8 / 9 : k) * A.coeff 4 * hSJ2 +
    (-8 / 9 : k) * A.coeff 3 * hSJ3

/-- Exact literal row-one load at coefficient `5`. -/
theorem cubicLoadRowOnePolynomial68_coeff_five_ordinaryOneEighty68
    (alpha gamma epsilon zeta eta : k) (A B c d e : k[X])
    (hA : A.natDegree ≤ 4) (hB : B.natDegree ≤ 0)
    (hc : c.natDegree ≤ 2) (hd : d.natDegree ≤ 1)
    (he : e.natDegree ≤ 3) :
    (cubicLoadRowOnePolynomial68 0 alpha 0 gamma 0 epsilon zeta eta
      A B c ((1 / 3 : k) • (A * B) + d) e).coeff 5 =
      4 * gamma * A.coeff 3 * e.coeff 3 +
        (8 / 3 : k) * gamma * A.coeff 4 * e.coeff 2 +
        (4 / 3 : k) * epsilon * A.coeff 4 * c.coeff 2 := by
  let D0 : k[X] := (1 / 3 : k) • (A * B) + d
  let Ur : k[X] := (2 / 3 * gamma : k) • B + C zeta
  have hloadEq :
      cubicLoadRowOnePolynomial68 0 alpha 0 gamma 0 epsilon zeta eta
        A B c D0 e =
      Ur * derivative D0 +
        (4 / 3 * gamma : k) • (A * derivative e - c * derivative c) +
        (2 / 3 * epsilon : k) • (A * derivative c) +
        (2 * epsilon : k) • derivative e -
        (2 / 3 * gamma : k) • (D0 * derivative B) := by
    apply (FaithfulSMul.algebraMap_injective k[X] (RatFunc k))
    simp only [cubicLoadRowOnePolynomial68, cubicLoadTPolynomial68,
      cubicLoadUPolynomial68, cubicLoadVPolynomial68, D0, Ur,
      zero_mul, zero_smul, smul_zero, add_zero, zero_add, sub_zero,
      derivative_add, derivative_sub, derivative_mul, derivative_pow,
      derivative_smul, derivative_C, one_mul, Polynomial.smul_eq_C_mul,
      map_add, map_sub, map_mul, map_pow, map_neg, map_zero,
      RatFunc.algebraMap_C, map_div₀, map_ofNat, map_natCast, map_one]
    ring
  have hD : D0.natDegree ≤ 4 := by simp only [D0]; compute_degree; omega
  have hUr : Ur.natDegree ≤ 0 := by simp only [Ur]; compute_degree; omega
  have hdere : (derivative e).natDegree ≤ 2 := by compute_degree; omega
  have hderc : (derivative c).natDegree ≤ 1 := by compute_degree; omega
  have hderB : derivative B = 0 := derivative_eq_zero.mpr (by omega)
  have hlow1 : (Ur * derivative D0).natDegree < 5 := by
    compute_degree
    omega
  have hAeRaw := congrArg (fun p : k[X] => p.coeff 1)
    (reflect_mul A (derivative e) hA hdere)
  rw [mul_coeff_one] at hAeRaw
  norm_num [coeff_reflect, coeff_derivative] at hAeRaw
  have hAe : (A * derivative e).coeff 5 =
      3 * A.coeff 3 * e.coeff 3 +
        2 * A.coeff 4 * e.coeff 2 := by
    linear_combination hAeRaw
  have hcder : (c * derivative c).natDegree < 5 := by compute_degree; omega
  have hAc := coeff_mul_derivative_at_bounds68 A c 4 2
    (by norm_num) hA hc
  norm_num at hAc
  have hAc' : (A * derivative c).coeff 5 =
      2 * A.coeff 4 * c.coeff 2 := by
    linear_combination hAc
  have helow : (derivative e).natDegree < 5 := by compute_degree; omega
  change (cubicLoadRowOnePolynomial68 0 alpha 0 gamma 0 epsilon zeta eta
      A B c D0 e).coeff 5 = _
  rw [hloadEq]
  simp only [hderB, mul_zero, zero_smul, sub_zero, coeff_add, coeff_sub,
    coeff_smul, coeff_zero, smul_eq_mul, hAe, hAc',
    coeff_eq_zero_of_natDegree_lt hlow1,
    coeff_eq_zero_of_natDegree_lt hcder,
    coeff_eq_zero_of_natDegree_lt helow]
  ring

/-- After the exact I3 jet loads cancel, row one gives a load-free cubic
edge constraint. -/
theorem fiveToSix_ordinaryOneEighty_rowOne_residual68
    (a a₃ b c x y e₂ gamma epsilon J₂ J₃ : k)
    (hc : c ≠ 0)
    (hface : b * y + c * x = 0)
    (hdisc : a * b ^ 2 + 3 * c ^ 2 = 0)
    (hJ2 : J₂ + 2 * epsilon * c +
        4 * gamma * e₂ = 0)
    (hJ3 : J₃ + 4 * gamma * y = 0)
    (hrow : (2 / 3 : k) * a * J₂ + a₃ * J₃ +
        (16 / 9 : k) * a * b ^ 2 * c - (8 / 3 : k) * a * x ^ 2 -
        (16 / 9 : k) * c ^ 3 + 8 * y ^ 2 +
        4 * gamma * a₃ * y + (8 / 3 : k) * gamma * a * e₂ +
        (4 / 3 : k) * epsilon * a * c = 0) :
    9 * y ^ 2 - 4 * c ^ 3 = 0 := by
  have hfaceSq : b ^ 2 * y ^ 2 - c ^ 2 * x ^ 2 = 0 := by
    linear_combination (b * y - c * x) * hface
  have hc2 : c ^ 2 ≠ 0 := pow_ne_zero 2 hc
  have hquadProd : c ^ 2 * (a * x ^ 2 + 3 * y ^ 2) = 0 := by
    linear_combination y ^ 2 * hdisc - a * hfaceSq
  have hquad : a * x ^ 2 + 3 * y ^ 2 = 0 :=
    (mul_eq_zero.mp hquadProd).resolve_left hc2
  have hscaled : (16 / 9 : k) * (9 * y ^ 2 - 4 * c ^ 3) = 0 := by
    linear_combination hrow - (2 / 3 : k) * a * hJ2 - a₃ * hJ3 -
      (16 / 9 : k) * c * hdisc + (8 / 3 : k) * hquad
  exact (mul_eq_zero.mp hscaled).resolve_left (by norm_num)

set_option maxHeartbeats 20000000 in
/-- Literal contracted source row.  It preserves the predecessor's rigid
I4 residual and appends both the new edge cubic and the exact constant-I3
equation. -/
theorem fiveToSix_offsetOneEighty_nonzero_rowOne_source_packet68
    (alpha gamma epsilon eta i4 i3 : k) (A B c d e : k[X])
    (hA : A.natDegree ≤ 4) (hB : B.natDegree ≤ 0)
    (hc : c.natDegree ≤ 2) (hd : d.natDegree ≤ 1)
    (he : e.natDegree ≤ 3)
    (ha : A.coeff 4 ≠ 0) (hb : B.coeff 0 ≠ 0)
    (hcTop : c.coeff 2 ≠ 0)
    (hx : d.coeff 1 ≠ 0) (hy : e.coeff 3 ≠ 0)
    (hface : B.coeff 0 * e.coeff 3 + c.coeff 2 * d.coeff 1 = 0)
    (hdisc : A.coeff 4 * B.coeff 0 ^ 2 + 3 * c.coeff 2 ^ 2 = 0)
    (hi4rigid : 27 * A.coeff 4 * i4 +
      32 * A.coeff 4 * B.coeff 0 ^ 3 +
        216 * d.coeff 1 * e.coeff 3 = 0)
    (hi3 : cubicFirstIntegralThreePolynomial68 0 0 gamma 0 epsilon 0
        A B c ((1 / 3 : k) • (A * B) + d) e = C i3)
    (hrowOne :
      let C0 := (1 / 3 : k) • A ^ 2 + c
      let D0 := (1 / 3 : k) • (A * B) + d
      let E0 := (1 / 27 : k) • A ^ 3 + (1 / 3 : k) • (A * c) + e
      lowerRowOnePolynomial68
        (integratedTPolynomial68 0 alpha 0 gamma epsilon A B C0 D0 E0)
        (integratedUPolynomial68 0 alpha 0 gamma 0 0 A B C0 D0 E0)
        (integratedVPolynomial68 0 alpha 0 gamma 0 epsilon eta
          A B C0 D0 E0) C0 D0 E0 = 0) :
    (27 * A.coeff 4 * i4 + 32 * A.coeff 4 * B.coeff 0 ^ 3 +
        216 * d.coeff 1 * e.coeff 3 = 0) ∧
      (9 * e.coeff 3 ^ 2 - 4 * c.coeff 2 ^ 3 = 0) ∧
      ((8 / 9 : k) *
          (-A.coeff 0 * B.coeff 0 * d.coeff 0 -
            B.coeff 0 ^ 2 * c.coeff 0 +
            3 * c.coeff 0 * e.coeff 0 +
            (3 / 2 : k) * d.coeff 0 ^ 2) +
        2 * epsilon * c.coeff 0 + 4 * gamma * e.coeff 0 -
        (2 / 3 : k) * gamma * B.coeff 0 ^ 2 = i3) := by
  let J : k[X] := secondaryResidualInvariantThreePolynomial68 A B c d e
  have hI3J : J + (2 * epsilon : k) • c +
      (4 * gamma : k) • e - (2 / 3 * gamma : k) • B ^ 2 = C i3 := by
    have hres := hi3
    rw [cubicFirstIntegralThreePolynomial68_fiveToSix_residualCoordinates]
      at hres
    simp only [zero_smul, zero_add] at hres
    simpa only [J, add_zero] using hres
  have hJdeg : J.natDegree ≤ 5 := by
    simp only [J, secondaryResidualInvariantThreePolynomial68]
    compute_degree
    omega
  have hc3 : c.coeff 3 = 0 :=
    coeff_eq_zero_of_natDegree_lt (hc.trans_lt (by norm_num))
  have hc4 : c.coeff 4 = 0 :=
    coeff_eq_zero_of_natDegree_lt (hc.trans_lt (by norm_num))
  have hc5 : c.coeff 5 = 0 :=
    coeff_eq_zero_of_natDegree_lt (hc.trans_lt (by norm_num))
  have he4 : e.coeff 4 = 0 :=
    coeff_eq_zero_of_natDegree_lt (he.trans_lt (by norm_num))
  have he5 : e.coeff 5 = 0 :=
    coeff_eq_zero_of_natDegree_lt (he.trans_lt (by norm_num))
  have hB2deg : (B ^ 2).natDegree ≤ 0 := by compute_degree; omega
  have hB2pos : ∀ j, 0 < j → (B ^ 2).coeff j = 0 := by
    intro j hj
    exact coeff_eq_zero_of_natDegree_lt (hB2deg.trans_lt hj)
  have h5 := congrArg (fun p : k[X] => p.coeff 5) hI3J
  norm_num [coeff_add, coeff_sub, coeff_smul, smul_eq_mul, coeff_C,
    hc5, he5, hB2pos 5 (by norm_num)] at h5
  have hJ5 : J.coeff 5 = 0 := h5
  have h4 := congrArg (fun p : k[X] => p.coeff 4) hI3J
  norm_num [coeff_add, coeff_sub, coeff_smul, smul_eq_mul, coeff_C,
    hc4, he4, hB2pos 4 (by norm_num)] at h4
  have hJ4 : J.coeff 4 = 0 := h4
  have h3 := congrArg (fun p : k[X] => p.coeff 3) hI3J
  norm_num [coeff_add, coeff_sub, coeff_smul, smul_eq_mul, coeff_C,
    hc3, hB2pos 3 (by norm_num)] at h3
  have hJ3 : J.coeff 3 +
      4 * gamma * e.coeff 3 = 0 := by linear_combination h3
  have hB22 : (B ^ 2).coeff 2 = 0 := hB2pos 2 (by norm_num)
  have h2 := congrArg (fun p : k[X] => p.coeff 2) hI3J
  norm_num [coeff_add, coeff_sub, coeff_smul, smul_eq_mul, coeff_C,
    hB22] at h2
  have hJ2 : J.coeff 2 +
      2 * epsilon * c.coeff 2 + 4 * gamma * e.coeff 2 = 0 := by
    linear_combination h2
  have hB20 : (B ^ 2).coeff 0 = B.coeff 0 ^ 2 := by
    simp only [pow_two, mul_coeff_zero]
  have h0 := congrArg (fun p : k[X] => p.coeff 0) hI3J
  norm_num [coeff_add, coeff_sub, coeff_smul, smul_eq_mul, coeff_C,
    hB20] at h0
  have hJ0 : J.coeff 0 = (8 / 9 : k) *
      (-A.coeff 0 * B.coeff 0 * d.coeff 0 -
        B.coeff 0 ^ 2 * c.coeff 0 + 3 * c.coeff 0 * e.coeff 0 +
        (3 / 2 : k) * d.coeff 0 ^ 2) := by
    simp only [J, secondaryResidualInvariantThreePolynomial68, coeff_add,
      coeff_sub, coeff_neg, coeff_smul,
      pow_two, mul_coeff_zero, smul_eq_mul]
    ring
  have hconstant : (8 / 9 : k) *
        (-A.coeff 0 * B.coeff 0 * d.coeff 0 -
          B.coeff 0 ^ 2 * c.coeff 0 + 3 * c.coeff 0 * e.coeff 0 +
          (3 / 2 : k) * d.coeff 0 ^ 2) +
      2 * epsilon * c.coeff 0 + 4 * gamma * e.coeff 0 -
      (2 / 3 : k) * gamma * B.coeff 0 ^ 2 = i3 := by
    rw [hJ0] at h0
    linear_combination h0
  let C0 : k[X] := (1 / 3 : k) • A ^ 2 + c
  let D0 : k[X] := (1 / 3 : k) • (A * B) + d
  let E0 : k[X] :=
    (1 / 27 : k) • A ^ 3 + (1 / 3 : k) • (A * c) + e
  change lowerRowOnePolynomial68
      (integratedTPolynomial68 0 alpha 0 gamma epsilon A B C0 D0 E0)
      (integratedUPolynomial68 0 alpha 0 gamma 0 0 A B C0 D0 E0)
      (integratedVPolynomial68 0 alpha 0 gamma 0 epsilon eta
        A B C0 D0 E0) C0 D0 E0 = 0 at hrowOne
  have hcoords := integratedPolynomial68_cubicCoordinates
    (0 : k) alpha 0 gamma 0 epsilon 0 eta A B c D0 e
  have hrowCoeff := congrArg (fun p : k[X] => p.coeff 5) hrowOne
  have hhom : cubicHomogeneousRowOnePolynomial68 A B c D0 e =
      secondaryResidualRowOnePolynomial68 A B c d e := by
    simpa only [D0] using
      cubicHomogeneousRowOnePolynomial68_residualCoordinates A B c d e
  have hres := secondaryResidualRowOnePolynomial68_coeff_five_ordinaryOneEighty68
    A B c d e hA hB hc hd he hJ5 hJ4
  have hload := cubicLoadRowOnePolynomial68_coeff_five_ordinaryOneEighty68
    alpha gamma epsilon 0 eta A B c d e hA hB hc hd he
  rw [hcoords.t_eq, hcoords.u_eq, hcoords.v_eq,
    cubicRowOnePolynomial68_split, coeff_add, hhom, hres, hload]
      at hrowCoeff
  simp only [coeff_zero] at hrowCoeff
  have hedge := fiveToSix_ordinaryOneEighty_rowOne_residual68
    (A.coeff 4) (A.coeff 3) (B.coeff 0) (c.coeff 2)
    (d.coeff 1) (e.coeff 3) (e.coeff 2) gamma epsilon
    (J.coeff 2) (J.coeff 3) hcTop hface hdisc hJ2 hJ3
    (by linear_combination hrowCoeff)
  exact ⟨hi4rigid, hedge, hconstant⟩

#print axioms fiveToSixRowOne_S_I3_identity68
#print axioms fiveToSixRowOne_eq_inner68
#print axioms secondaryResidualRowOnePolynomial68_coeff_five_ordinaryOneEighty68
#print axioms cubicLoadRowOnePolynomial68_coeff_five_ordinaryOneEighty68
#print axioms fiveToSix_ordinaryOneEighty_rowOne_residual68
#print axioms fiveToSix_offsetOneEighty_nonzero_rowOne_source_packet68

end LaterDeepLowerParentFiveToSixOffsetOneEightyOrdinaryRowOne68

end Max11DegreeRoutes
