import Sol68FiveToSixCuspLoadedLowerRowZetaFirstUniformJetEndpointB3EqualityEpsilonSupportQZeroFceZeroHTopScratch

/-! # Pure divisibility split on the zero-`Fce` branch -/

noncomputable section

open Polynomial

namespace Max11DegreeRoutes

section FiveToSixCuspLoadedLowerRowZetaFirstUniformJetEndpointB3EqualityEpsilonSupportQZeroFceZeroDivisibility68

variable {k : Type*} [Field k] [CharZero k] [IsAlgClosed k]

set_option maxHeartbeats 30000000
set_option maxRecDepth 10000
set_option linter.unusedSectionVars false
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false

/-- The two global zero-`Fce` identities put both `d*(2c+3γ)` and
`H*(2c+3γ)` in the ideal generated by `B`. -/
theorem fiveToSix_qZero_Fce_zero_basic_divisibilities68
    (gamma epsilon kappa : k) (A B c d e : k[X])
    (hF : ((B * e + c * d) - (1 / 9 : k) • B ^ 3) +
        (3 / 2 * gamma : k) • d + (3 / 4 * epsilon : k) • B = 0)
    (hP : FiveToSixQZeroFceZeroRowTwoIntegral68 gamma epsilon A B c d e =
      C kappa) :
    let Cg := (2 : k) • c + C (3 * gamma)
    let H := FiveToSixQZeroFceZeroH68 B c d
    B ∣ Cg * d ∧ B ∣ Cg * H := by
  let Cg := (2 : k) • c + C (3 * gamma)
  let H := FiveToSixQZeroFceZeroH68 B c d
  let Delta := fiveToSixCuspDiscriminantPolynomial68 A B c
  change B ∣ Cg * d ∧ B ∣ Cg * H
  have halg := fiveToSix_qZero_Fce_zero_rowTwo_Delta_H_algebra68
    gamma epsilon kappa A B c d e hF hP
  change (2 : k) • (B ^ 2 * Delta) - (12 : k) • (B ^ 3 * d) +
      (9 * gamma : k) • (B ^ 2 * c) + (3 * kappa : k) • B -
    (6 : k) • (c * H) - (9 * gamma : k) • H = 0 at halg
  constructor
  · refine ⟨-(2 : k) • e + (2 / 9 : k) • B ^ 2 -
        C (3 / 2 * epsilon), ?_⟩
    dsimp only [Cg]
    apply (FaithfulSMul.algebraMap_injective k[X] (RatFunc k))
    have hF' := congrArg (algebraMap k[X] (RatFunc k)) hF
    simp only [Polynomial.smul_eq_C_mul, map_add, map_sub, map_mul, map_pow,
      map_neg, map_zero, RatFunc.algebraMap_C] at hF' ⊢
    simp only [map_div₀, map_ofNat, map_one] at hF' ⊢
    ring_nf at hF' ⊢
    linear_combination (2 : RatFunc k) * hF'
  · refine ⟨(1 / 3 : k) • ((2 : k) • (B * Delta) -
        (12 : k) • (B ^ 2 * d) + (9 * gamma : k) • (B * c) +
        C (3 * kappa)), ?_⟩
    dsimp only [Cg]
    apply (FaithfulSMul.algebraMap_injective k[X] (RatFunc k))
    have halg' := congrArg (algebraMap k[X] (RatFunc k)) halg
    simp only [Polynomial.smul_eq_C_mul, map_add, map_sub, map_mul, map_pow,
      map_neg, map_zero, RatFunc.algebraMap_C] at halg' ⊢
    simp only [map_div₀, map_ofNat, map_one] at halg' ⊢
    ring_nf at halg' ⊢
    linear_combination (-1 / 3 : RatFunc k) * halg'

/-- This is the honest algebraic branch point.  If `B` has no common
factor with `2c+3γ`, Euclid cancellation forces `B` to divide both `d`
and `H`; otherwise a nontrivial common-factor branch remains. -/
theorem fiveToSix_qZero_Fce_zero_coprime_or_commonFactor68
    (gamma epsilon kappa : k) (A B c d e : k[X])
    (hF : ((B * e + c * d) - (1 / 9 : k) • B ^ 3) +
        (3 / 2 * gamma : k) • d + (3 / 4 * epsilon : k) • B = 0)
    (hP : FiveToSixQZeroFceZeroRowTwoIntegral68 gamma epsilon A B c d e =
      C kappa) :
    let Cg := (2 : k) • c + C (3 * gamma)
    let H := FiveToSixQZeroFceZeroH68 B c d
    ¬ IsCoprime B Cg ∨ (B ∣ d ∧ B ∣ H) := by
  let Cg := (2 : k) • c + C (3 * gamma)
  let H := FiveToSixQZeroFceZeroH68 B c d
  change ¬ IsCoprime B Cg ∨ (B ∣ d ∧ B ∣ H)
  have hdiv := fiveToSix_qZero_Fce_zero_basic_divisibilities68
    gamma epsilon kappa A B c d e hF hP
  change B ∣ Cg * d ∧ B ∣ Cg * H at hdiv
  by_cases hcop : IsCoprime B Cg
  · exact Or.inr ⟨hcop.dvd_of_dvd_mul_left hdiv.1,
      hcop.dvd_of_dvd_mul_left hdiv.2⟩
  · exact Or.inl hcop

#print axioms fiveToSix_qZero_Fce_zero_basic_divisibilities68
#print axioms fiveToSix_qZero_Fce_zero_coprime_or_commonFactor68

end FiveToSixCuspLoadedLowerRowZetaFirstUniformJetEndpointB3EqualityEpsilonSupportQZeroFceZeroDivisibility68

end Max11DegreeRoutes
